/* global console, process */
import { execFileSync } from "node:child_process";
import subpathManifest from "./subpath-export-manifest.json" with { type: "json" };
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const root = process.cwd();
const workspace = mkdtempSync(join(tmpdir(), "crewai-ts-pack-smoke-"));

try {
  const tarballName = execFileSync("npm", ["pack", "--silent"], {
    cwd: root,
    encoding: "utf8",
  }).trim().split("\n").at(-1);
  if (!tarballName) {
    throw new Error("npm pack did not return a tarball name.");
  }

  const appDir = join(workspace, "app");
  mkdirSync(appDir, { recursive: true });
  writeFileSync(join(appDir, "package.json"), `${JSON.stringify({
    type: "module",
    dependencies: {
      "@crewai-ts/core": join(root, tarballName),
    },
    devDependencies: {
      "@types/node": "^25.9.1",
      typescript: "^6.0.3",
    },
  }, null, 2)}\n`);
  writeFileSync(join(appDir, "tsconfig.json"), `${JSON.stringify({
    compilerOptions: {
      target: "ES2024",
      module: "NodeNext",
      moduleResolution: "NodeNext",
      strict: true,
      experimentalDecorators: false,
      skipLibCheck: true,
    },
    include: ["index.ts"],
  }, null, 2)}\n`);
  writeFileSync(join(appDir, "index.mjs"), [
    "import { Agent, Crew, LLM, Process, Task, __version__ } from '@crewai-ts/core';",
    "import { CrewBase, agent, before_kickoff, crew, task } from '@crewai-ts/core/project';",
    "import { CrewBase as DeepCrewBase } from '@crewai-ts/core/project/crew_base';",
    "import { AgentConfig as CrewBaseAgentConfig, CrewBaseMeta, CallableT, close_mcp_server, get_mcp_tools, load_configurations, load_yaml, map_all_agent_variables, map_all_task_variables } from '@crewai-ts/core/project/crew_base';",
    "import { agent as deepAgent } from '@crewai-ts/core/project/annotations';",
    "import { P as AnnotationP, P2, R as AnnotationR, R2, SelfT, T as AnnotationT } from '@crewai-ts/core/project/annotations';",
    "import { DecoratedMethod, AgentMethod, TaskMethod, CrewMetadata, CrewInstance, CrewClass, OutputJsonClass, OutputPydanticClass } from '@crewai-ts/core/project/wrappers';",
    "import { memoize } from '@crewai-ts/core/project/utils';",
    "import { TaskOutput } from '@crewai-ts/core/tasks/task_output';",
    "import { OutputFormat } from '@crewai-ts/core/tasks/output_format';",
    "import { ConditionalTask } from '@crewai-ts/core/tasks/conditional_task';",
    "import { LLMGuardrail } from '@crewai-ts/core/tasks/llm_guardrail';",
    "import { HallucinationGuardrail } from '@crewai-ts/core/tasks/hallucination_guardrail';",
    "import { Crew as SingularCrew } from '@crewai-ts/core/crew';",
    "import { Task as SingularTask } from '@crewai-ts/core/task';",
    "import { BaseTool, CrewStructuredTool, EnvVar } from '@crewai-ts/core/tools';",
    "import { BaseTool as DeepBaseTool } from '@crewai-ts/core/tools/base_tool';",
    "import { CrewStructuredTool as DeepStructuredTool } from '@crewai-ts/core/tools/structured_tool';",
    "import { AddImageTool } from '@crewai-ts/core/tools/agent_tools/add_image_tool';",
    "import { AgentTools } from '@crewai-ts/core/tools/agent_tools/agent_tools';",
    "import { AskQuestionTool } from '@crewai-ts/core/tools/agent_tools/ask_question_tool';",
    "import { BaseAgentTool } from '@crewai-ts/core/tools/agent_tools/base_agent_tools';",
    "import { DelegateWorkTool } from '@crewai-ts/core/tools/agent_tools/delegate_work_tool';",
    "import { ReadFileTool } from '@crewai-ts/core/tools/agent_tools/read_file_tool';",
    "import { CacheTools } from '@crewai-ts/core/tools/cache_tools/cache_tools';",
    "import { ToolCalling } from '@crewai-ts/core/tools/tool_calling';",
    "import { ToolResult } from '@crewai-ts/core/tools/tool_types';",
    "import { ToolUsage } from '@crewai-ts/core/tools/tool_usage';",
    "import { Telemetry } from '@crewai-ts/core/telemetry/telemetry';",
    "import { CREWAI_TELEMETRY_BASE_URL } from '@crewai-ts/core/telemetry/constants';",
    "import { close_span } from '@crewai-ts/core/telemetry/utils';",
    "import { PlanStep, TodoList } from '@crewai-ts/core/utilities/planning_types';",
    "import { MIN_REQUIRED_VERSION, chat_loop, flush_input, get_user_input, handle_user_input, initialize_chat_llm, load_crew_and_name, run_chat, show_loading } from '@crewai-ts/core/utilities/crew_chat';",
    "import { PlanPerTask, PlannerTaskPydanticOutput } from '@crewai-ts/core/utilities/planning_handler';",
    "import { AgentReasoning, FUNCTION_SCHEMA } from '@crewai-ts/core/utilities/reasoning_handler';",
    "import { NOT_SPECIFIED } from '@crewai-ts/core/utilities/constants';",
    "import { GuardrailCallable, GuardrailType, GuardrailsType } from '@crewai-ts/core/utilities/guardrail_types';",
    "import { ImportedDefinition, adapter, require as requireOptionalDependency } from '@crewai-ts/core/utilities/import_utils';",
    "import { ColoredText, PrinterColor } from '@crewai-ts/core/utilities/printer';",
    "import { Serializable, SerializablePrimitive } from '@crewai-ts/core/utilities/serialization';",
    "import { ENV_VARS, JSON_URL, MODELS, PROVIDERS } from '@crewai-ts/core/constants';",
    "import { check_version, get_latest_version_from_pypi, is_current_version_yanked, is_newer_version_available } from '@crewai-ts/core/version';",
    "import { RPMController } from '@crewai-ts/core/utilities/rpm_controller';",
    "import { JsonSchemaInfo, create_model_from_schema } from '@crewai-ts/core/utilities/pydantic_schema_utils';",
    "import { CreateConverterKwargs, create_converter } from '@crewai-ts/core/utilities/converter';",
    "import { StepExecutionContext, StepResult } from '@crewai-ts/core/utilities/step_execution_context';",
    "import { StreamingState, TaskInfo, create_async_chunk_generator, create_chunk_generator, create_streaming_state, logger as streamingLogger, register_cleanup, signal_end, signal_error } from '@crewai-ts/core/utilities/streaming';",
    "import { LLMMessage } from '@crewai-ts/core/utilities/types';",
    "import { ACTION_INPUT_ONLY_REGEX, ACTION_INPUT_REGEX, ACTION_REGEX } from '@crewai-ts/core/agents/constants';",
    "import { BaseAgent, PlatformApp, PlatformAppOrAction } from '@crewai-ts/core/agents/agent_builder/base_agent';",
    "import { BaseAgentExecutor } from '@crewai-ts/core/agents/agent_builder/base_agent_executor';",
    "import { AgentExecutor, AgentExecutorState, CrewAgentExecutorFlow } from '@crewai-ts/core/experimental/agent_executor';",
    "import { OutputConverter } from '@crewai-ts/core/agents/agent_builder/utilities/base_output_converter';",
    "import { TokenProcess } from '@crewai-ts/core/agents/agent_builder/utilities/base_token_process';",
    "import { CrewAgentExecutor } from '@crewai-ts/core/agents/crew_agent_executor';",
    "import { PlannerObserver } from '@crewai-ts/core/agents/planner_observer';",
    "import { StepExecutor } from '@crewai-ts/core/agents/step_executor';",
    "import { SummaryContent, NativeToolCallResult, aget_llm_response, build_tool_calls_assistant_message, check_native_tool_support, enforce_rpm_limit, execute_single_native_tool_call, extract_tool_call_info, format_answer, get_llm_response, handle_agent_action_core, handle_context_length, handle_max_iterations_exceeded, handle_output_parser_exception, handle_unknown_error, is_context_length_exceeded, is_inside_event_loop, is_tool_call_list, load_agent_from_repository, parse_tool_call_args, parse_tools, process_llm_response, setup_native_tools, show_agent_logs, summarize_messages, track_delegation_if_needed } from '@crewai-ts/core/utilities/agent_utils';",
    "import { extract_available_exports, extract_tools_metadata, fetch_crews, get_crew_instance, get_crews, get_flow_instance, get_flows, is_valid_tool } from '@crewai-ts/core/utilities/project_utils';",
    "import { BaseAgentAdapter } from '@crewai-ts/core/agents/agent_adapters/base_agent_adapter';",
    "import { BaseToolAdapter } from '@crewai-ts/core/agents/agent_adapters/base_tool_adapter';",
    "import { BaseConverterAdapter } from '@crewai-ts/core/agents/agent_adapters/base_converter_adapter';",
    "import { OpenAIAgentAdapter, Runner } from '@crewai-ts/core/agents/agent_adapters/openai_agents/openai_adapter';",
    "import { OpenAIAgentToolAdapter } from '@crewai-ts/core/agents/agent_adapters/openai_agents/openai_agent_tool_adapter';",
    "import { OpenAIConverterAdapter } from '@crewai-ts/core/agents/agent_adapters/openai_agents/structured_output_converter';",
    "import { OpenAITool } from '@crewai-ts/core/agents/agent_adapters/openai_agents/protocols';",
    "import { LangGraphAgentAdapter } from '@crewai-ts/core/agents/agent_adapters/langgraph/langgraph_adapter';",
    "import { LangGraphToolAdapter } from '@crewai-ts/core/agents/agent_adapters/langgraph/langgraph_tool_adapter';",
    "import { LangGraphConverterAdapter } from '@crewai-ts/core/agents/agent_adapters/langgraph/structured_output_converter';",
    "import { LangGraphPrebuiltModule } from '@crewai-ts/core/agents/agent_adapters/langgraph/protocols';",
    "import { DisclosureLevel, ResourceDirName, Skill } from '@crewai-ts/core/skills/models';",
    "import { JsonProvider } from '@crewai-ts/core/state/provider/json_provider';",
    "import { BaseProvider as StateBaseProvider } from '@crewai-ts/core/state/provider/core';",
    "import { Auth0Provider } from '@crewai-ts/core/auth/providers/auth0';",
    "import { BaseProvider } from '@crewai-ts/core/auth/providers/base_provider';",
    "import { get_user_id, is_first_execution, is_tracing_enabled_in_context, mark_first_execution_completed, reset_tracing_enabled, safe_serialize_to_dict, set_suppress_tracing_messages, set_tracing_enabled, should_enable_tracing, truncate_messages } from '@crewai-ts/core/events/listeners/tracing/utils';",
    "import { LLMCallHookContext } from '@crewai-ts/core/hooks/llm_hooks';",
    "import { BeforeLLMCallHook, Hook, ReturnT } from '@crewai-ts/core/hooks/types';",
    "import { AfterLLMCallHookMethod, BeforeToolCallHookMethod } from '@crewai-ts/core/hooks/wrappers';",
    "import { BaseEventListener, CheckpointBaseEvent, CheckpointForkBaseEvent, CheckpointRestoreBaseEvent, CircularDependencyError, CrewAIEventsBus, Depends, EventListener, FlowEvent, HandlerGraph, ReasoningEvent, ToolUsageEvent, build_execution_plan, crewaiEventBus, crewai_event_bus } from '@crewai-ts/core/events/event_bus';",
    "import { is_async_handler, is_call_handler_safe } from '@crewai-ts/core/events/utils/handlers';",
    "import { TraceBatch, TraceBatchManager } from '@crewai-ts/core/events/listeners/tracing/trace_batch_manager';",
    "import { AsyncHandler, AsyncHandlerSet, ExecutionPlan, Handler, SyncHandler, SyncHandlerSet } from '@crewai-ts/core/events/types/event_bus_types';",
    "import { SIGNAL_EVENT_TYPES, SignalEvent, on_signal, signal_event_adapter } from '@crewai-ts/core/events/types/system_events';",
    "import { ENV_CONTEXT_EVENT_TYPES, EnvContextEvent, env_context_event_adapter } from '@crewai-ts/core/events/types/env_events';",
    "import { MismatchBehavior, handle_empty_pop, handle_mismatch, resume_task_scope } from '@crewai-ts/core/events/event_context';",
    "import { AgentAggregatedEvaluationResult, AgentEvaluationResult, AggregationStrategy, BaseEvaluator, EvaluationScore, MetricCategory } from '@crewai-ts/core/experimental/evaluation/base_evaluator';",
    "import { AgentEvaluator, ExecutionState, create_default_evaluator } from '@crewai-ts/core/experimental/evaluation/agent_evaluator';",
    "import { ParameterExtractionEvaluator, ToolInvocationEvaluator, ToolSelectionEvaluator } from '@crewai-ts/core/experimental/evaluation/metrics/tools_metrics';",
    "import { ReasoningEfficiencyEvaluator, ReasoningPatternType } from '@crewai-ts/core/experimental/evaluation/metrics/reasoning_metrics';",
    "import { ExperimentResult, ExperimentResults } from '@crewai-ts/core/experimental/evaluation/experiment/result';",
    "import { EvaluationTraceCallback, create_evaluation_callbacks } from '@crewai-ts/core/experimental/evaluation/evaluation_listener';",
    "import { assert_experiment_no_regression, assert_experiment_successfully, run_experiment } from '@crewai-ts/core/experimental/evaluation/testing';",
    "import { AsyncExecutorContext, ExecutorContext, HumanInputProvider, get_provider, reset_provider, set_provider } from '@crewai-ts/core/core/providers/human_input';",
    "import { ContentProcessorProvider, NoOpContentProcessor, get_processor, process_content, set_processor } from '@crewai-ts/core/core/providers/content_processor';",
    "import { sanitizeToolName } from '@crewai-ts/core/utilities/string_utils';",
    "import { UsageMetrics } from '@crewai-ts/core/types/usage_metrics';",
    "import { SerializableCallable } from '@crewai-ts/core/types/callback';",
    "import { CheckpointConfig } from '@crewai-ts/core/state';",
    "import { CheckpointEventType, apply_checkpoint } from '@crewai-ts/core/state/checkpoint_config';",
    "import { build_task_prompt_with_schema, prepare_tools } from '@crewai-ts/core/agent/utils';",
    "import { TaskExecutionData, setup_agents } from '@crewai-ts/core/crews/utils';",
    "",
    "console.log(Boolean(Agent), Boolean(Crew), Boolean(Task), Boolean(LLM), __version__, Process.sequential);",
    "",
  ].join("\n"));
  writeFileSync(join(appDir, "index.ts"), [
    "import { Agent, Crew, LLM, Process, Task, __version__ } from '@crewai-ts/core';",
    "import { CrewBase, agent, before_kickoff, crew, task } from '@crewai-ts/core/project';",
    "import { CrewBase as DeepCrewBase } from '@crewai-ts/core/project/crew_base';",
    "import { AgentConfig as CrewBaseAgentConfig, CrewBaseMeta, CallableT, close_mcp_server, get_mcp_tools, load_configurations, load_yaml, map_all_agent_variables, map_all_task_variables } from '@crewai-ts/core/project/crew_base';",
    "import { agent as deepAgent } from '@crewai-ts/core/project/annotations';",
    "import { P as AnnotationP, P2, R as AnnotationR, R2, SelfT, T as AnnotationT } from '@crewai-ts/core/project/annotations';",
    "import { DecoratedMethod, AgentMethod, TaskMethod, CrewMetadata, CrewInstance, CrewClass, OutputJsonClass, OutputPydanticClass } from '@crewai-ts/core/project/wrappers';",
    "import { memoize } from '@crewai-ts/core/project/utils';",
    "import { TaskOutput } from '@crewai-ts/core/tasks/task_output';",
    "import { OutputFormat } from '@crewai-ts/core/tasks/output_format';",
    "import { ConditionalTask } from '@crewai-ts/core/tasks/conditional_task';",
    "import { LLMGuardrail } from '@crewai-ts/core/tasks/llm_guardrail';",
    "import { HallucinationGuardrail } from '@crewai-ts/core/tasks/hallucination_guardrail';",
    "import { Crew as SingularCrew } from '@crewai-ts/core/crew';",
    "import { Task as SingularTask } from '@crewai-ts/core/task';",
    "import { BaseTool, CrewStructuredTool, EnvVar } from '@crewai-ts/core/tools';",
    "import { BaseTool as DeepBaseTool } from '@crewai-ts/core/tools/base_tool';",
    "import { CrewStructuredTool as DeepStructuredTool } from '@crewai-ts/core/tools/structured_tool';",
    "import { AddImageTool } from '@crewai-ts/core/tools/agent_tools/add_image_tool';",
    "import { AgentTools } from '@crewai-ts/core/tools/agent_tools/agent_tools';",
    "import { AskQuestionTool } from '@crewai-ts/core/tools/agent_tools/ask_question_tool';",
    "import { BaseAgentTool } from '@crewai-ts/core/tools/agent_tools/base_agent_tools';",
    "import { DelegateWorkTool } from '@crewai-ts/core/tools/agent_tools/delegate_work_tool';",
    "import { ReadFileTool } from '@crewai-ts/core/tools/agent_tools/read_file_tool';",
    "import { CacheTools } from '@crewai-ts/core/tools/cache_tools/cache_tools';",
    "import { ToolCalling } from '@crewai-ts/core/tools/tool_calling';",
    "import { ToolResult } from '@crewai-ts/core/tools/tool_types';",
    "import { ToolUsage } from '@crewai-ts/core/tools/tool_usage';",
    "import { Telemetry } from '@crewai-ts/core/telemetry/telemetry';",
    "import { CREWAI_TELEMETRY_BASE_URL } from '@crewai-ts/core/telemetry/constants';",
    "import { close_span } from '@crewai-ts/core/telemetry/utils';",
    "import { PlanStep, TodoList } from '@crewai-ts/core/utilities/planning_types';",
    "import { MIN_REQUIRED_VERSION, chat_loop, flush_input, get_user_input, handle_user_input, initialize_chat_llm, load_crew_and_name, run_chat, show_loading } from '@crewai-ts/core/utilities/crew_chat';",
    "import { PlanPerTask, PlannerTaskPydanticOutput } from '@crewai-ts/core/utilities/planning_handler';",
    "import { AgentReasoning, FUNCTION_SCHEMA } from '@crewai-ts/core/utilities/reasoning_handler';",
    "import { NOT_SPECIFIED } from '@crewai-ts/core/utilities/constants';",
    "import { GuardrailCallable, GuardrailType, GuardrailsType } from '@crewai-ts/core/utilities/guardrail_types';",
    "import { ImportedDefinition, adapter, require as requireOptionalDependency } from '@crewai-ts/core/utilities/import_utils';",
    "import { ColoredText, PrinterColor } from '@crewai-ts/core/utilities/printer';",
    "import { Serializable, SerializablePrimitive } from '@crewai-ts/core/utilities/serialization';",
    "import { ENV_VARS, JSON_URL, MODELS, PROVIDERS } from '@crewai-ts/core/constants';",
    "import { check_version, get_latest_version_from_pypi, is_current_version_yanked, is_newer_version_available } from '@crewai-ts/core/version';",
    "import { RPMController } from '@crewai-ts/core/utilities/rpm_controller';",
    "import { JsonSchemaInfo, create_model_from_schema } from '@crewai-ts/core/utilities/pydantic_schema_utils';",
    "import { CreateConverterKwargs, create_converter } from '@crewai-ts/core/utilities/converter';",
    "import { StepExecutionContext, StepResult } from '@crewai-ts/core/utilities/step_execution_context';",
    "import { StreamingState, TaskInfo, create_async_chunk_generator, create_chunk_generator, create_streaming_state, logger as streamingLogger, register_cleanup, signal_end, signal_error } from '@crewai-ts/core/utilities/streaming';",
    "import { LLMMessage } from '@crewai-ts/core/utilities/types';",
    "import { ACTION_INPUT_ONLY_REGEX, ACTION_INPUT_REGEX, ACTION_REGEX } from '@crewai-ts/core/agents/constants';",
    "import { BaseAgent, PlatformApp, PlatformAppOrAction } from '@crewai-ts/core/agents/agent_builder/base_agent';",
    "import { BaseAgentExecutor } from '@crewai-ts/core/agents/agent_builder/base_agent_executor';",
    "import { AgentExecutor, AgentExecutorState, CrewAgentExecutorFlow } from '@crewai-ts/core/experimental/agent_executor';",
    "import { OutputConverter } from '@crewai-ts/core/agents/agent_builder/utilities/base_output_converter';",
    "import { TokenProcess } from '@crewai-ts/core/agents/agent_builder/utilities/base_token_process';",
    "import { CrewAgentExecutor } from '@crewai-ts/core/agents/crew_agent_executor';",
    "import { PlannerObserver } from '@crewai-ts/core/agents/planner_observer';",
    "import { StepExecutor } from '@crewai-ts/core/agents/step_executor';",
    "import { SummaryContent, NativeToolCallResult, aget_llm_response, build_tool_calls_assistant_message, check_native_tool_support, enforce_rpm_limit, execute_single_native_tool_call, extract_tool_call_info, format_answer, get_llm_response, handle_agent_action_core, handle_context_length, handle_max_iterations_exceeded, handle_output_parser_exception, handle_unknown_error, is_context_length_exceeded, is_inside_event_loop, is_tool_call_list, load_agent_from_repository, parse_tool_call_args, parse_tools, process_llm_response, setup_native_tools, show_agent_logs, summarize_messages, track_delegation_if_needed } from '@crewai-ts/core/utilities/agent_utils';",
    "import { extract_available_exports, extract_tools_metadata, fetch_crews, get_crew_instance, get_crews, get_flow_instance, get_flows, is_valid_tool } from '@crewai-ts/core/utilities/project_utils';",
    "import { BaseAgentAdapter } from '@crewai-ts/core/agents/agent_adapters/base_agent_adapter';",
    "import { BaseToolAdapter } from '@crewai-ts/core/agents/agent_adapters/base_tool_adapter';",
    "import { BaseConverterAdapter } from '@crewai-ts/core/agents/agent_adapters/base_converter_adapter';",
    "import { OpenAIAgentAdapter, Runner } from '@crewai-ts/core/agents/agent_adapters/openai_agents/openai_adapter';",
    "import { OpenAIAgentToolAdapter } from '@crewai-ts/core/agents/agent_adapters/openai_agents/openai_agent_tool_adapter';",
    "import { OpenAIConverterAdapter } from '@crewai-ts/core/agents/agent_adapters/openai_agents/structured_output_converter';",
    "import { OpenAITool } from '@crewai-ts/core/agents/agent_adapters/openai_agents/protocols';",
    "import { LangGraphAgentAdapter } from '@crewai-ts/core/agents/agent_adapters/langgraph/langgraph_adapter';",
    "import { LangGraphToolAdapter } from '@crewai-ts/core/agents/agent_adapters/langgraph/langgraph_tool_adapter';",
    "import { LangGraphConverterAdapter } from '@crewai-ts/core/agents/agent_adapters/langgraph/structured_output_converter';",
    "import { LangGraphPrebuiltModule } from '@crewai-ts/core/agents/agent_adapters/langgraph/protocols';",
    "import { DisclosureLevel, ResourceDirName, Skill } from '@crewai-ts/core/skills/models';",
    "import { JsonProvider } from '@crewai-ts/core/state/provider/json_provider';",
    "import { BaseProvider as StateBaseProvider } from '@crewai-ts/core/state/provider/core';",
    "import { Auth0Provider } from '@crewai-ts/core/auth/providers/auth0';",
    "import { BaseProvider } from '@crewai-ts/core/auth/providers/base_provider';",
    "import { get_user_id, is_first_execution, is_tracing_enabled_in_context, mark_first_execution_completed, reset_tracing_enabled, safe_serialize_to_dict, set_suppress_tracing_messages, set_tracing_enabled, should_enable_tracing, truncate_messages } from '@crewai-ts/core/events/listeners/tracing/utils';",
    "import { LLMCallHookContext } from '@crewai-ts/core/hooks/llm_hooks';",
    "import { BeforeLLMCallHook, Hook, ReturnT } from '@crewai-ts/core/hooks/types';",
    "import { AfterLLMCallHookMethod, BeforeToolCallHookMethod } from '@crewai-ts/core/hooks/wrappers';",
    "import { BaseEventListener, CheckpointBaseEvent, CheckpointForkBaseEvent, CheckpointRestoreBaseEvent, CircularDependencyError, CrewAIEventsBus, Depends, EventListener, FlowEvent, HandlerGraph, ReasoningEvent, ToolUsageEvent, build_execution_plan, crewaiEventBus, crewai_event_bus } from '@crewai-ts/core/events/event_bus';",
    "import { is_async_handler, is_call_handler_safe } from '@crewai-ts/core/events/utils/handlers';",
    "import { TraceBatch, TraceBatchManager } from '@crewai-ts/core/events/listeners/tracing/trace_batch_manager';",
    "import { AsyncHandler, AsyncHandlerSet, ExecutionPlan, Handler, SyncHandler, SyncHandlerSet } from '@crewai-ts/core/events/types/event_bus_types';",
    "import { SIGNAL_EVENT_TYPES, SignalEvent, on_signal, signal_event_adapter } from '@crewai-ts/core/events/types/system_events';",
    "import { ENV_CONTEXT_EVENT_TYPES, EnvContextEvent, env_context_event_adapter } from '@crewai-ts/core/events/types/env_events';",
    "import { MismatchBehavior, handle_empty_pop, handle_mismatch, resume_task_scope } from '@crewai-ts/core/events/event_context';",
    "import { AgentAggregatedEvaluationResult, AgentEvaluationResult, AggregationStrategy, BaseEvaluator, EvaluationScore, MetricCategory } from '@crewai-ts/core/experimental/evaluation/base_evaluator';",
    "import { AgentEvaluator, ExecutionState, create_default_evaluator } from '@crewai-ts/core/experimental/evaluation/agent_evaluator';",
    "import { ParameterExtractionEvaluator, ToolInvocationEvaluator, ToolSelectionEvaluator } from '@crewai-ts/core/experimental/evaluation/metrics/tools_metrics';",
    "import { ReasoningEfficiencyEvaluator, ReasoningPatternType } from '@crewai-ts/core/experimental/evaluation/metrics/reasoning_metrics';",
    "import { ExperimentResult, ExperimentResults } from '@crewai-ts/core/experimental/evaluation/experiment/result';",
    "import { EvaluationTraceCallback, create_evaluation_callbacks } from '@crewai-ts/core/experimental/evaluation/evaluation_listener';",
    "import { assert_experiment_no_regression, assert_experiment_successfully, run_experiment } from '@crewai-ts/core/experimental/evaluation/testing';",
    "import { AsyncExecutorContext, ExecutorContext, HumanInputProvider, get_provider, reset_provider, set_provider } from '@crewai-ts/core/core/providers/human_input';",
    "import { ContentProcessorProvider, NoOpContentProcessor, get_processor, process_content, set_processor } from '@crewai-ts/core/core/providers/content_processor';",
    "import { sanitizeToolName } from '@crewai-ts/core/utilities/string_utils';",
    "import { UsageMetrics } from '@crewai-ts/core/types/usage_metrics';",
    "import { SerializableCallable } from '@crewai-ts/core/types/callback';",
    "import { CheckpointConfig } from '@crewai-ts/core/state';",
    "import { CheckpointEventType, apply_checkpoint } from '@crewai-ts/core/state/checkpoint_config';",
    "import { build_task_prompt_with_schema, prepare_tools } from '@crewai-ts/core/agent/utils';",
    "import { TaskExecutionData, setup_agents } from '@crewai-ts/core/crews/utils';",
    "",
    "const researchAgent = new Agent({",
    "  role: 'Researcher',",
    "  goal: 'Find facts',",
    "  backstory: 'Careful analyst',",
    "  llm: () => 'done',",
    "});",
    "const researchTask = new Task({ description: 'Research', expected_output: 'A brief', agent: researchAgent });",
    "const researchCrew = new Crew({ agents: [researchAgent], tasks: [researchTask], process: Process.sequential });",
    "const llm = new LLM({ model: 'gpt-4o-mini' });",
    "",
    "",
  ].join("\n"));

  execFileSync("npm", ["install", "--silent"], { cwd: appDir, stdio: "inherit" });
  writeFileSync(join(appDir, "all-exports.mjs"), [
    `const subpaths = ${JSON.stringify(subpathManifest)};`,
    "await import('@crewai-ts/core');",
    "for (const subpath of subpaths) {",
    "  await import(`@crewai-ts/core/${subpath}`);",
    "}",
    "console.log('all exports import ok');",
  ].join("\n"));
  const allExportsOutput = execFileSync("node", ["all-exports.mjs"], { cwd: appDir, encoding: "utf8" }).trim();
  if (allExportsOutput !== "all exports import ok") {
    throw new Error(`Unexpected all exports import output: ${allExportsOutput}`);
  }
  const output = execFileSync("node", ["index.mjs"], { cwd: appDir, encoding: "utf8" }).trim();
  if (output !== "true true true true 1.14.6 sequential") {
    throw new Error(`Unexpected package import output: ${output}`);
  }
  execFileSync("npx", ["tsc", "--noEmit"], { cwd: appDir, stdio: "inherit" });
  console.log("pack smoke ok");
} finally {
  rmSync(workspace, { recursive: true, force: true });
}
