/* global console, process */
import { execFileSync } from "node:child_process";
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const root = process.cwd();
const workspace = mkdtempSync(join(tmpdir(), "crewai-ts-pack-smoke-"));

try {
  const tarballName = execFileSync("npm", ["pack", "--silent"], {
    cwd: root,
    encoding: "utf8",
  }).trim().split("\n").at(-1);
  if (!tarballName) {
    throw new Error("npm pack did not return a tarball name.");
  }

  const appDir = join(workspace, "app");
  mkdirSync(appDir, { recursive: true });
  writeFileSync(join(appDir, "package.json"), `${JSON.stringify({
    type: "module",
    dependencies: {
      "@crewai-ts/core": join(root, tarballName),
    },
    devDependencies: {
      "@types/node": "^25.9.1",
      typescript: "^6.0.3",
    },
  }, null, 2)}\n`);
  writeFileSync(join(appDir, "tsconfig.json"), `${JSON.stringify({
    compilerOptions: {
      target: "ES2024",
      module: "NodeNext",
      moduleResolution: "NodeNext",
      strict: true,
      experimentalDecorators: false,
      skipLibCheck: true,
    },
    include: ["index.ts"],
  }, null, 2)}\n`);
  writeFileSync(join(appDir, "index.mjs"), [
    "import { Agent, Crew, LLM, Process, Task, __version__ } from '@crewai-ts/core';",
    "import { CrewBase, agent, before_kickoff, crew, task } from '@crewai-ts/core/project';",
    "import { Flow, start } from '@crewai-ts/core/flow';",
    "import { ConsoleProvider as FlowConsoleProvider, FlowStructure as FlowStructureMarker, HumanFeedbackProvider as HumanFeedbackProviderMarker, HumanFeedbackResult as HumanFeedbackResultMarker, InputProvider as InputProviderMarker, InputResponse as InputResponseMarker, PendingFeedbackContext as PendingFeedbackContextMarker, flow_config, visualize_flow_structure } from '@crewai-ts/core/flow';",
    "import { F as FlowRuntimeF, FlowMeta, LockedDictProxy, LockedListProxy, StateProxy } from '@crewai-ts/core/flow/flow';",
    "import { DistilledLessons, F as HumanFeedbackF, HumanFeedbackConfig as HumanFeedbackConfigMarker, HumanFeedbackMethod, HumanFeedbackMethod as HumanFeedbackMethodMarker, PreReviewResult } from '@crewai-ts/core/flow/human_feedback';",
    "import { EdgeInfo, FlowStructureInfo, MethodInfo, StateFieldInfo, StateSchemaInfo } from '@crewai-ts/core/flow/flow_serializer';",
    "import { JsonFlowPersistence, persist } from '@crewai-ts/core/flow/persistence';",
    "import { SQLiteFlowPersistence } from '@crewai-ts/core/flow/persistence/sqlite';",
    "import { ConsoleInputProvider } from '@crewai-ts/core/flow/input_provider';",
    "import { CrewBase as DeepCrewBase } from '@crewai-ts/core/project/crew_base';",
    "import { AgentConfig as CrewBaseAgentConfig, CrewBaseMeta, CallableT, close_mcp_server, get_mcp_tools, load_configurations, load_yaml, map_all_agent_variables, map_all_task_variables } from '@crewai-ts/core/project/crew_base';",
    "import { agent as deepAgent } from '@crewai-ts/core/project/annotations';",
    "import { P as AnnotationP, P2, R as AnnotationR, R2, SelfT, T as AnnotationT } from '@crewai-ts/core/project/annotations';",
    "import { DecoratedMethod, AgentMethod, TaskMethod, CrewMetadata, CrewInstance, CrewClass, OutputJsonClass, OutputPydanticClass } from '@crewai-ts/core/project/wrappers';",
    "import { memoize } from '@crewai-ts/core/project/utils';",
    "import { TaskOutput } from '@crewai-ts/core/tasks/task_output';",
    "import { OutputFormat } from '@crewai-ts/core/tasks/output_format';",
    "import { ConditionalTask } from '@crewai-ts/core/tasks/conditional_task';",
    "import { LLMGuardrail } from '@crewai-ts/core/tasks/llm_guardrail';",
    "import { HallucinationGuardrail } from '@crewai-ts/core/tasks/hallucination_guardrail';",
    "import { LLM as SubpathLLM, ANTHROPIC_PREFIXES, AccumulatedToolArgs, Delta, FunctionArgs, MAX_CONTEXT, MIN_CONTEXT, StreamingChoices } from '@crewai-ts/core/llm';",
    "import { AnthropicModels, AzureModels, BedrockModels, GeminiModels, OpenAIModels } from '@crewai-ts/core/llms/constants';",
    "import { extract_tool_info, log_tool_conversion, safe_tool_conversion, sanitize_function_name, validate_function_name } from '@crewai-ts/core/llms/providers/utils/common';",
    "import { Crew as SingularCrew } from '@crewai-ts/core/crew';",
    "import { Task as SingularTask } from '@crewai-ts/core/task';",
    "import { BaseTool, CrewStructuredTool, EnvVar, tool as toolDecorator } from '@crewai-ts/core/tools';",
    "import { BaseTool as DeepBaseTool } from '@crewai-ts/core/tools/base_tool';",
    "import { CrewStructuredTool as DeepStructuredTool } from '@crewai-ts/core/tools/structured_tool';",
    "import { AddImageTool } from '@crewai-ts/core/tools/agent_tools/add_image_tool';",
    "import { AgentTools } from '@crewai-ts/core/tools/agent_tools/agent_tools';",
    "import { AskQuestionTool } from '@crewai-ts/core/tools/agent_tools/ask_question_tool';",
    "import { BaseAgentTool } from '@crewai-ts/core/tools/agent_tools/base_agent_tools';",
    "import { DelegateWorkTool } from '@crewai-ts/core/tools/agent_tools/delegate_work_tool';",
    "import { ReadFileTool } from '@crewai-ts/core/tools/agent_tools/read_file_tool';",
    "import { CacheTools } from '@crewai-ts/core/tools/cache_tools/cache_tools';",
    "import { MCPNativeTool } from '@crewai-ts/core/tools/mcp_native_tool';",
    "import { MCPToolWrapper } from '@crewai-ts/core/tools/mcp_tool_wrapper';",
    "import { ToolCalling } from '@crewai-ts/core/tools/tool_calling';",
    "import { ToolResult } from '@crewai-ts/core/tools/tool_types';",
    "import { ToolUsage } from '@crewai-ts/core/tools/tool_usage';",
    "import { RecallMemoryTool, RememberTool, create_memory_tools } from '@crewai-ts/core/tools/memory_tools';",
    "import { Telemetry } from '@crewai-ts/core/telemetry/telemetry';",
    "import { CREWAI_TELEMETRY_BASE_URL } from '@crewai-ts/core/telemetry/constants';",
    "import { close_span } from '@crewai-ts/core/telemetry/utils';",
    "import { PlanStep, TodoList } from '@crewai-ts/core/utilities/planning_types';",
    "import { MIN_REQUIRED_VERSION, chat_loop, flush_input, get_user_input, handle_user_input, initialize_chat_llm, load_crew_and_name, run_chat, show_loading } from '@crewai-ts/core/utilities/crew_chat';",
    "import { PlanPerTask, PlannerTaskPydanticOutput } from '@crewai-ts/core/utilities/planning_handler';",
    "import { AgentReasoning, FUNCTION_SCHEMA } from '@crewai-ts/core/utilities/reasoning_handler';",
    "import { NOT_SPECIFIED } from '@crewai-ts/core/utilities/constants';",
    "import { GuardrailCallable, GuardrailType, GuardrailsType } from '@crewai-ts/core/utilities/guardrail_types';",
    "import { ImportedDefinition, adapter, require as requireOptionalDependency } from '@crewai-ts/core/utilities/import_utils';",
    "import { ColoredText, PrinterColor } from '@crewai-ts/core/utilities/printer';",
    "import { Serializable, SerializablePrimitive } from '@crewai-ts/core/utilities/serialization';",
    "import { ENV_VARS, JSON_URL, MODELS, PROVIDERS } from '@crewai-ts/core/constants';",
    "import { check_version, get_latest_version_from_pypi, is_current_version_yanked, is_newer_version_available } from '@crewai-ts/core/version';",
    "import { RPMController } from '@crewai-ts/core/utilities/rpm_controller';",
    "import { JsonSchemaInfo, create_model_from_schema } from '@crewai-ts/core/utilities/pydantic_schema_utils';",
    "import { CreateConverterKwargs, create_converter } from '@crewai-ts/core/utilities/converter';",
    "import { StepExecutionContext, StepResult } from '@crewai-ts/core/utilities/step_execution_context';",
    "import { StreamingState, TaskInfo, create_async_chunk_generator, create_chunk_generator, create_streaming_state, logger as streamingLogger, register_cleanup, signal_end, signal_error } from '@crewai-ts/core/utilities/streaming';",
    "import { LLMMessage } from '@crewai-ts/core/utilities/types';",
    "import { ACTION_INPUT_ONLY_REGEX, ACTION_INPUT_REGEX, ACTION_REGEX } from '@crewai-ts/core/agents/constants';",
    "import { BaseAgent, PlatformApp, PlatformAppOrAction } from '@crewai-ts/core/agents/agent_builder/base_agent';",
    "import { BaseAgentExecutor } from '@crewai-ts/core/agents/agent_builder/base_agent_executor';",
    "import { AgentExecutor, AgentExecutorState, CrewAgentExecutorFlow } from '@crewai-ts/core/experimental/agent_executor';",
    "import { OutputConverter } from '@crewai-ts/core/agents/agent_builder/utilities/base_output_converter';",
    "import { TokenProcess } from '@crewai-ts/core/agents/agent_builder/utilities/base_token_process';",
    "import { CrewAgentExecutor } from '@crewai-ts/core/agents/crew_agent_executor';",
    "import { PlannerObserver } from '@crewai-ts/core/agents/planner_observer';",
    "import { StepExecutor } from '@crewai-ts/core/agents/step_executor';",
    "import { SummaryContent, NativeToolCallResult, aget_llm_response, build_tool_calls_assistant_message, check_native_tool_support, enforce_rpm_limit, execute_single_native_tool_call, extract_tool_call_info, format_answer, get_llm_response, handle_agent_action_core, handle_context_length, handle_max_iterations_exceeded, handle_output_parser_exception, handle_unknown_error, is_context_length_exceeded, is_inside_event_loop, is_tool_call_list, load_agent_from_repository, parse_tool_call_args, parse_tools, process_llm_response, setup_native_tools, show_agent_logs, summarize_messages, track_delegation_if_needed } from '@crewai-ts/core/utilities/agent_utils';",
    "import { extract_available_exports, extract_tools_metadata, fetch_crews, get_crew_instance, get_crews, get_flow_instance, get_flows, is_valid_tool } from '@crewai-ts/core/utilities/project_utils';",
    "import { BaseAgentAdapter } from '@crewai-ts/core/agents/agent_adapters/base_agent_adapter';",
    "import { BaseToolAdapter } from '@crewai-ts/core/agents/agent_adapters/base_tool_adapter';",
    "import { BaseConverterAdapter } from '@crewai-ts/core/agents/agent_adapters/base_converter_adapter';",
    "import { OpenAIAgentAdapter, Runner } from '@crewai-ts/core/agents/agent_adapters/openai_agents/openai_adapter';",
    "import { OpenAIAgentToolAdapter } from '@crewai-ts/core/agents/agent_adapters/openai_agents/openai_agent_tool_adapter';",
    "import { OpenAIConverterAdapter } from '@crewai-ts/core/agents/agent_adapters/openai_agents/structured_output_converter';",
    "import { OpenAITool } from '@crewai-ts/core/agents/agent_adapters/openai_agents/protocols';",
    "import { LangGraphAgentAdapter } from '@crewai-ts/core/agents/agent_adapters/langgraph/langgraph_adapter';",
    "import { LangGraphToolAdapter } from '@crewai-ts/core/agents/agent_adapters/langgraph/langgraph_tool_adapter';",
    "import { LangGraphConverterAdapter } from '@crewai-ts/core/agents/agent_adapters/langgraph/structured_output_converter';",
    "import { LangGraphPrebuiltModule } from '@crewai-ts/core/agents/agent_adapters/langgraph/protocols';",
    "import { CodeInterpreterFileResult, CodeInterpreterLogResult, CodeInterpreterResult, ComputerUseResult, FileSearchResult, FileSearchResultItem, OpenAICompletion, ReasoningSummary, ResponsesAPIResult, WebSearchResult } from '@crewai-ts/core/llms/providers/openai/completion';",
    "import { OPENAI_COMPATIBLE_PROVIDERS, OpenAICompatibleCompletion, ProviderConfig } from '@crewai-ts/core/llms/providers/openai_compatible/completion';",
    "import { ANTHROPIC_FILES_API_BETA, ANTHROPIC_STRUCTURED_OUTPUTS_BETA, AnthropicCompletion, AnthropicThinkingConfig, AnthropicToolSearchConfig, NATIVE_STRUCTURED_OUTPUT_MODELS, TOOL_SEARCH_TOOL_TYPES } from '@crewai-ts/core/llms/providers/anthropic/completion';",
    "import { AzureCompletion, AzureCompletionParams } from '@crewai-ts/core/llms/providers/azure/completion';",
    "import { BedrockCompletion, BedrockConverseRequestBody, BedrockConverseStreamRequestBody, ConverseToolTypeDef, STRUCTURED_OUTPUT_TOOL_NAME, ToolInputSchema, ToolSpec } from '@crewai-ts/core/llms/providers/bedrock/completion';",
    "import { MCPToolResolver } from '@crewai-ts/core/mcp/tool_resolver';",
    "import { MCPClient } from '@crewai-ts/core/mcp/client';",
    "import { MCPServerConfig, MCPServerStdio, MCPServerHTTP, MCPServerSSE } from '@crewai-ts/core/mcp/config';",
    "import { StaticToolFilter, ToolFilter, ToolFilterContext } from '@crewai-ts/core/mcp/filters';",
    "import { BaseTransport, MCPReadStream, MCPWriteStream, TransportType } from '@crewai-ts/core/mcp/transports/base';",
    "import { HTTPTransport } from '@crewai-ts/core/mcp/transports/http';",
    "import { SSETransport } from '@crewai-ts/core/mcp/transports/sse';",
    "import { StdioTransport } from '@crewai-ts/core/mcp/transports/stdio';",
    "import { Memory } from '@crewai-ts/core/memory';",
    "import { Memory as DeepMemory } from '@crewai-ts/core/memory/unified_memory';",
    "import { MemoryScope } from '@crewai-ts/core/memory/memory_scope';",
    "import { MemoryConfig, MemoryMatch, MemoryRecord, ScopeInfo, compute_composite_score, embed_text, embed_texts } from '@crewai-ts/core/memory/types';",
    "import { EncodingFlow, EncodingState, ItemState } from '@crewai-ts/core/memory/encoding_flow';",
    "import { RecallFlow, RecallState } from '@crewai-ts/core/memory/recall_flow';",
    "import { DEFAULT_VECTOR_DIM as QdrantEdgeDefaultVectorDim, QdrantEdgeStorage, VECTOR_NAME } from '@crewai-ts/core/memory/storage/qdrant_edge_storage';",
    "import { DEFAULT_VECTOR_DIM as LanceDefaultVectorDim, LanceDBStorage } from '@crewai-ts/core/memory/storage/lancedb_storage';",
    "import { join_scope_paths, normalize_scope_path, sanitize_scope_name } from '@crewai-ts/core/memory/utils';",
    "import { DisclosureLevel, ResourceDirName, Skill } from '@crewai-ts/core/skills/models';",
    "import { ChromaDBConfig } from '@crewai-ts/core/rag/chromadb/config';",
    "import { DEFAULT_COLLECTION, DEFAULT_DATABASE, DEFAULT_TENANT, INVALID_CHARS_PATTERN, IPV4_PATTERN, MAX_COLLECTION_LENGTH, MIN_COLLECTION_LENGTH } from '@crewai-ts/core/rag/chromadb/constants';",
    "import { BaseRecord } from '@crewai-ts/core/rag/chromadb/types';",
    "import { ChromaDBClientType, ChromaDBCollectionCreateParams, ChromaDBCollectionSearchParams, ChromaEmbeddingFunctionWrapper, ExtractedSearchParams, PreparedDocuments } from '@crewai-ts/core/rag/chromadb/types';",
    "import { SearchResult } from '@crewai-ts/core/rag/core/types';",
    "import { DType32, Documents, Embeddable, PyEmbedding } from '@crewai-ts/core/rag/core/types';",
    "import { DEFAULT_VECTOR_PARAMS } from '@crewai-ts/core/rag/qdrant/constants';",
    "import { QdrantEmbeddingFunctionWrapper, PreparedSearchParams } from '@crewai-ts/core/rag/qdrant/types';",
    "import { RagConfigType } from '@crewai-ts/core/rag/config/types';",
    "import { AllowedEmbeddingProviders, EmbedderConfig, Embedding, ProviderSpec } from '@crewai-ts/core/rag/embeddings/types';",
    "import { set_rag_config } from '@crewai-ts/core/rag/config/utils';",
    "import { BaseClient, BaseCollectionAddParams, BaseCollectionParams } from '@crewai-ts/core/rag/core/base_client';",
    "import { BaseEmbeddingsCallable } from '@crewai-ts/core/rag/core/base_embeddings_callable';",
    "import { ClientMethodMismatchError } from '@crewai-ts/core/rag/core/exceptions';",
    "import { OpenAIProviderSpec } from '@crewai-ts/core/rag/embeddings/providers/openai/types';",
    "import { AzureProviderSpec } from '@crewai-ts/core/rag/embeddings/providers/microsoft/types';",
    "import { BedrockProviderSpec } from '@crewai-ts/core/rag/embeddings/providers/aws/types';",
    "import { GenerativeAiProviderConfig, VertexAIProviderConfig, VertexAIProviderSpec } from '@crewai-ts/core/rag/embeddings/providers/google/types';",
    "import { MissingChromaDBConfig, MissingQdrantConfig } from '@crewai-ts/core/rag/config/optional_imports/providers';",
    "import { ChromaFactoryModule, QdrantFactoryModule } from '@crewai-ts/core/rag/config/optional_imports/protocols';",
    "import { AzureProvider, AzureProviderConfig, CohereProvider, CohereProviderConfig, CustomEmbeddingFunction, CustomProvider, CustomProviderConfig, GoogleGenAIVertexEmbeddingFunction, GenerativeAiProvider, HuggingFaceProvider, HuggingFaceProviderConfig, InstructorProvider, InstructorProviderConfig, JinaProvider, JinaProviderConfig, OllamaProvider, OllamaProviderConfig, ONNXProvider, ONNXProviderConfig, OpenAIProvider, OpenAIProviderConfig, OpenCLIPProvider, OpenCLIPProviderConfig, QdrantClient, RoboflowProvider, RoboflowProviderConfig, SentenceTransformerProvider, SentenceTransformerProviderConfig, Text2VecProvider, Text2VecProviderConfig, VertexAIProvider, VoyageAIEmbeddingFunction, VoyageAIProvider, VoyageAIProviderConfig, WatsonXEmbeddingFunction, WatsonXProvider, WatsonXProviderConfig } from '@crewai-ts/core/rag/embeddings/providers/openai/openai_provider';",
    "import { BedrockProvider, create_aws_session } from '@crewai-ts/core/rag/embeddings/providers/aws/bedrock';",
    "import { JsonProvider } from '@crewai-ts/core/state/provider/json_provider';",
    "import { BaseProvider as StateBaseProvider } from '@crewai-ts/core/state/provider/core';",
    "import { Auth0Provider } from '@crewai-ts/core/auth/providers/auth0';",
    "import { BaseProvider } from '@crewai-ts/core/auth/providers/base_provider';",
    "import { ArtifactNotFoundError, ContentTypeNegotiationError, ERROR_MESSAGES, JSONParseError, NegotiatedContentTypes, negotiate_content_types, validate_content_type } from '@crewai-ts/core/a2a/errors';",
    "import { Action, STANDARD_CATALOG_COMPONENTS } from '@crewai-ts/core/a2a/extensions/a2ui/catalog';",
    "import { A2UIMessage, BeginRendering, extract_a2ui_json_objects } from '@crewai-ts/core/a2a/extensions/a2ui/models';",
    "import { A2UIMessageV09, BASIC_CATALOG_COMPONENTS, TextV09, extract_a2ui_v09_json_objects } from '@crewai-ts/core/a2a/extensions/a2ui/v0_9';",
    "import { A2UIClientExtension, A2UIConversationState, is_v08_message, is_v09_message } from '@crewai-ts/core/a2a/extensions/a2ui/client_extension';",
    "import { A2UIServerExtension, A2UI_EXTENSION_URI, A2UI_MIME_TYPE } from '@crewai-ts/core/a2a/extensions/a2ui/server_extension';",
    "import { A2UIValidationError, validate_a2ui_message, validate_catalog_components_v09 } from '@crewai-ts/core/a2a/extensions/a2ui/validator';",
    "import { APPLICATION_A2UI_JSON, TEXT_PLAIN, get_part_content_type } from '@crewai-ts/core/a2a/utils/content_type';",
    "import { RedisCacheConfig, cancel, cancellable, execute, execute_with_extensions, list_tasks } from '@crewai-ts/core/a2a/utils/task';",
    "import { A2AClientConfigTypes, A2AConfigTypes, create_agent_response_model, extract_a2a_agent_ids_from_config, get_a2a_agents_and_response_model } from '@crewai-ts/core/a2a/utils/response_model';",
    "import { APIKeyServerAuth, CoercedSecretStr, JWTAlgorithm, MTLSServerAuth, OAuth2ServerAuth } from '@crewai-ts/core/a2a/auth/server_schemes';",
    "import { JSONFormatter, LogContext, configure_json_logging, get_logger } from '@crewai-ts/core/a2a/utils/logging';",
    "import { SigningAlgorithm, get_key_id_from_signature, sign_agent_card, verify_agent_card_signature } from '@crewai-ts/core/a2a/utils/agent_card_signing';",
    "import { DelegationContext, DelegationState, wrap_agent_with_a2a_instance } from '@crewai-ts/core/a2a/wrapper';",
    "import { A2AExtension, ConversationState, ExtensionRegistry, ValidatedA2AExtension } from '@crewai-ts/core/a2a/extensions/base';",
    "import { ExtensionsMiddleware, create_extension_registry_from_config, get_extensions_from_config, validate_required_extensions } from '@crewai-ts/core/a2a/extensions/registry';",
    "import { ExtensionContext, ServerExtension, ServerExtensionRegistry } from '@crewai-ts/core/a2a/extensions/server';",
    "import { configure_auth_client, parse_www_authenticate, retry_on_401, validate_auth_against_agent_card } from '@crewai-ts/core/a2a/auth/utils';",
    "import { aexecute_a2a_delegation, execute_a2a_delegation, get_handler } from '@crewai-ts/core/a2a/utils/delegation';",
    "import { afetch_agent_card, fetch_agent_card, inject_a2a_server_methods } from '@crewai-ts/core/a2a/utils/agent_card';",
    "import { SendMessageEvent, TaskStateResult } from '@crewai-ts/core/a2a/task_helpers';",
    "import { MAX_RESUBSCRIBE_ATTEMPTS, RESUBSCRIBE_BACKOFF_BASE, StreamingHandler } from '@crewai-ts/core/a2a/updates/streaming/handler';",
    "import { PushNotificationConfig, SignatureInput } from '@crewai-ts/core/a2a/updates/push_notifications/config';",
    "import { WebhookSignatureConfig, WebhookSignatureMode } from '@crewai-ts/core/a2a/updates/push_notifications/signature';",
    "import { NegotiationSource, TransportProtocol } from '@crewai-ts/core/a2a/utils/transport';",
    "import { build_a2ui_system_prompt, build_a2ui_v09_system_prompt } from '@crewai-ts/core/a2a/extensions/a2ui/prompt';",
    "import { AgentResponseProtocol, HANDLER_REGISTRY, HandlerType, PartsDict, PartsMetadataDict, PollingHandlerType, ProtocolVersion, PushNotificationHandlerType, StreamingHandlerType, Url } from '@crewai-ts/core/a2a/types';",
    "import { BaseHandlerKwargs, CommonParams, PollingHandlerKwargs, PushNotificationHandlerKwargs, PushNotificationResultStore, StreamingHandlerKwargs, UpdateHandler, extract_common_params } from '@crewai-ts/core/a2a/updates/base';",
    "import { get_user_id, is_first_execution, is_tracing_enabled_in_context, mark_first_execution_completed, reset_tracing_enabled, safe_serialize_to_dict, set_suppress_tracing_messages, set_tracing_enabled, should_enable_tracing, truncate_messages } from '@crewai-ts/core/events/listeners/tracing/utils';",
    "import { BG_CARD, BG_DARK, BORDER_SUBTLE, CREWAI_ORANGE, CSSExtension, DARK_GRAY, GRAY, JSExtension, TEXT_PRIMARY, TEXT_SECONDARY, WHITE, calculate_node_positions, render_interactive } from '@crewai-ts/core/flow/visualization/renderers/interactive';",
    "import { NodeMetadata, StructureEdge } from '@crewai-ts/core/flow/visualization/types';",
    "import { LLMCallHookContext } from '@crewai-ts/core/hooks/llm_hooks';",
    "import { BeforeLLMCallHook, Hook, ReturnT } from '@crewai-ts/core/hooks/types';",
    "import { BaseInterceptor, U as HookU } from '@crewai-ts/core/llms/hooks/base';",
    "import { AsyncHTTPTransport, HTTPTransportKwargs } from '@crewai-ts/core/llms/hooks/transport';",
    "import { AfterLLMCallHookMethod, BeforeToolCallHookMethod } from '@crewai-ts/core/hooks/wrappers';",
    "import { BaseEventListener, CheckpointBaseEvent, CheckpointForkBaseEvent, CheckpointRestoreBaseEvent, CircularDependencyError, CrewAIEventsBus, Depends, EventListener, FlowEvent, HandlerGraph, ReasoningEvent, ToolUsageEvent, build_execution_plan, crewaiEventBus, crewai_event_bus } from '@crewai-ts/core/events/event_bus';",
    "import { is_async_handler, is_call_handler_safe } from '@crewai-ts/core/events/utils/handlers';",
    "import { TraceBatch, TraceBatchManager } from '@crewai-ts/core/events/listeners/tracing/trace_batch_manager';",
    "import { AsyncHandler, AsyncHandlerSet, ExecutionPlan, Handler, SyncHandler, SyncHandlerSet } from '@crewai-ts/core/events/types/event_bus_types';",
    "import { SIGNAL_EVENT_TYPES, SignalEvent, on_signal, signal_event_adapter } from '@crewai-ts/core/events/types/system_events';",
    "import { ENV_CONTEXT_EVENT_TYPES, EnvContextEvent, env_context_event_adapter } from '@crewai-ts/core/events/types/env_events';",
    "import { MismatchBehavior, handle_empty_pop, handle_mismatch, resume_task_scope } from '@crewai-ts/core/events/event_context';",
    "import { AgentAggregatedEvaluationResult, AgentEvaluationResult, AggregationStrategy, BaseEvaluator, EvaluationScore, MetricCategory } from '@crewai-ts/core/experimental/evaluation/base_evaluator';",
    "import { AgentEvaluator, ExecutionState, create_default_evaluator } from '@crewai-ts/core/experimental/evaluation/agent_evaluator';",
    "import { ParameterExtractionEvaluator, ToolInvocationEvaluator, ToolSelectionEvaluator } from '@crewai-ts/core/experimental/evaluation/metrics/tools_metrics';",
    "import { ReasoningEfficiencyEvaluator, ReasoningPatternType } from '@crewai-ts/core/experimental/evaluation/metrics/reasoning_metrics';",
    "import { ExperimentResult, ExperimentResults } from '@crewai-ts/core/experimental/evaluation/experiment/result';",
    "import { EvaluationTraceCallback, create_evaluation_callbacks } from '@crewai-ts/core/experimental/evaluation/evaluation_listener';",
    "import { assert_experiment_no_regression, assert_experiment_successfully, run_experiment } from '@crewai-ts/core/experimental/evaluation/testing';",
    "import { AsyncExecutorContext, ExecutorContext, HumanInputProvider, get_provider, reset_provider, set_provider } from '@crewai-ts/core/core/providers/human_input';",
    "import { ContentProcessorProvider, NoOpContentProcessor, get_processor, process_content, set_processor } from '@crewai-ts/core/core/providers/content_processor';",
    "import { sanitizeToolName } from '@crewai-ts/core/utilities/string_utils';",
    "import { UsageMetrics } from '@crewai-ts/core/types/usage_metrics';",
    "import { SerializableCallable } from '@crewai-ts/core/types/callback';",
    "import { StringKnowledgeSource } from '@crewai-ts/core/knowledge/source/string_knowledge_source';",
    "import { CheckpointConfig } from '@crewai-ts/core/state';",
    "import { CheckpointEventType, apply_checkpoint } from '@crewai-ts/core/state/checkpoint_config';",
    "import { FlowMethodData, FlowExecutionData, PendingListenerKey } from '@crewai-ts/core/flow/types';",
    "import { AND_CONDITION, OR_CONDITION } from '@crewai-ts/core/flow/constants';",
    "import { FlowMethod, StartMethod, FlowConditionType } from '@crewai-ts/core/flow/flow_wrappers';",
    "import { dfs_ancestors, is_ancestor, is_flow_condition_dict, is_flow_condition_list, is_flow_method, is_flow_method_callable, is_flow_method_name, is_simple_flow_condition, process_router_paths } from '@crewai-ts/core/flow/utils';",
    "import { build_task_prompt_with_schema, prepare_tools } from '@crewai-ts/core/agent/utils';",
    "import { TaskExecutionData, setup_agents } from '@crewai-ts/core/crews/utils';",
    "void CrewBase; void agent; void before_kickoff; void crew; void task;",
    "void Flow; void start; void FlowConsoleProvider; void FlowStructureMarker; void HumanFeedbackProviderMarker; void HumanFeedbackResultMarker; void InputProviderMarker; void InputResponseMarker; void PendingFeedbackContextMarker; void flow_config; void visualize_flow_structure; void FlowRuntimeF; void FlowMeta; void LockedDictProxy; void LockedListProxy; void StateProxy; void DistilledLessons; void HumanFeedbackF; void HumanFeedbackConfigMarker; void HumanFeedbackMethod; void HumanFeedbackMethodMarker; void PreReviewResult; void EdgeInfo; void FlowStructureInfo; void MethodInfo; void StateFieldInfo; void StateSchemaInfo; void JsonFlowPersistence; void persist; void SubpathLLM; void ANTHROPIC_PREFIXES; void AccumulatedToolArgs; void Delta; void FunctionArgs; void MAX_CONTEXT; void MIN_CONTEXT; void StreamingChoices; void AnthropicModels; void AzureModels; void BedrockModels; void GeminiModels; void OpenAIModels; void extract_tool_info; void log_tool_conversion; void safe_tool_conversion; void sanitize_function_name; void validate_function_name; void SingularCrew; void SingularTask;",
    "void SQLiteFlowPersistence; void ConsoleInputProvider; void DeepCrewBase; void CrewBaseAgentConfig; void CrewBaseMeta; void CallableT; void close_mcp_server; void get_mcp_tools; void load_configurations; void load_yaml; void map_all_agent_variables; void map_all_task_variables; void deepAgent; void AnnotationP; void P2; void AnnotationR; void R2; void SelfT; void AnnotationT; void DecoratedMethod; void AgentMethod; void TaskMethod; void CrewMetadata; void CrewInstance; void CrewClass; void OutputJsonClass; void OutputPydanticClass; void memoize; void TaskOutput; void OutputFormat; void ConditionalTask; void LLMGuardrail; void HallucinationGuardrail;",
    "void DeepBaseTool; void DeepStructuredTool; void AddImageTool; void AgentTools; void AskQuestionTool; void BaseAgentTool; void DelegateWorkTool; void ReadFileTool; void CacheTools; void MCPNativeTool; void MCPToolWrapper; void ToolCalling; void ToolResult; void ToolUsage; void RecallMemoryTool; void RememberTool; void create_memory_tools; void Telemetry; void CREWAI_TELEMETRY_BASE_URL; void close_span; void PlanStep; void TodoList; void MIN_REQUIRED_VERSION; void chat_loop; void flush_input; void get_user_input; void handle_user_input; void initialize_chat_llm; void load_crew_and_name; void run_chat; void show_loading; void PlanPerTask; void PlannerTaskPydanticOutput; void AgentReasoning; void FUNCTION_SCHEMA; void NOT_SPECIFIED; void GuardrailCallable; void GuardrailType; void GuardrailsType; void ImportedDefinition; void adapter; void requireOptionalDependency; void ColoredText; void PrinterColor; void Serializable; void SerializablePrimitive; void RPMController; void JsonSchemaInfo; void create_model_from_schema; void CreateConverterKwargs; void create_converter; void StepExecutionContext; void StepResult; void StreamingState; void TaskInfo; void create_async_chunk_generator; void create_chunk_generator; void create_streaming_state; void streamingLogger; void register_cleanup; void signal_end; void signal_error; void LLMMessage; void ACTION_INPUT_ONLY_REGEX; void ACTION_REGEX; void ACTION_INPUT_REGEX; void BaseAgent; void PlatformApp; void PlatformAppOrAction; void BaseAgentExecutor; void AgentExecutor; void AgentExecutorState; void CrewAgentExecutorFlow; void OutputConverter; void TokenProcess; void CrewAgentExecutor; void PlannerObserver; void StepExecutor; void SummaryContent; void NativeToolCallResult; void aget_llm_response; void build_tool_calls_assistant_message; void check_native_tool_support; void enforce_rpm_limit; void execute_single_native_tool_call; void extract_tool_call_info; void format_answer; void get_llm_response; void handle_agent_action_core; void handle_context_length; void handle_max_iterations_exceeded; void handle_output_parser_exception; void handle_unknown_error; void is_context_length_exceeded; void is_inside_event_loop; void is_tool_call_list; void load_agent_from_repository; void parse_tool_call_args; void parse_tools; void process_llm_response; void setup_native_tools; void show_agent_logs; void summarize_messages; void track_delegation_if_needed; void extract_available_exports; void extract_tools_metadata; void fetch_crews; void get_crew_instance; void get_crews; void get_flow_instance; void get_flows; void is_valid_tool; void BaseAgentAdapter; void BaseToolAdapter; void BaseConverterAdapter; void OpenAIAgentAdapter; void Runner; void OpenAIAgentToolAdapter; void OpenAIConverterAdapter; void OpenAITool; void LangGraphAgentAdapter; void LangGraphToolAdapter; void LangGraphConverterAdapter; void LangGraphPrebuiltModule;",
    "void CodeInterpreterFileResult; void CodeInterpreterLogResult; void CodeInterpreterResult; void ComputerUseResult; void FileSearchResult; void FileSearchResultItem; void OpenAICompletion; void ReasoningSummary; void ResponsesAPIResult; void WebSearchResult; void OPENAI_COMPATIBLE_PROVIDERS; void OpenAICompatibleCompletion; void ProviderConfig; void ANTHROPIC_FILES_API_BETA; void ANTHROPIC_STRUCTURED_OUTPUTS_BETA; void AnthropicCompletion; void AnthropicThinkingConfig; void AnthropicToolSearchConfig; void NATIVE_STRUCTURED_OUTPUT_MODELS; void TOOL_SEARCH_TOOL_TYPES; void AzureCompletion; void AzureCompletionParams; void BedrockCompletion; void BedrockConverseRequestBody; void BedrockConverseStreamRequestBody; void ConverseToolTypeDef; void STRUCTURED_OUTPUT_TOOL_NAME; void ToolInputSchema; void ToolSpec;",
    "void MCPToolResolver; void MCPClient; void MCPServerConfig; void MCPServerStdio; void MCPServerHTTP; void MCPServerSSE; void StaticToolFilter; void ToolFilter; void ToolFilterContext; void BaseTransport; void MCPReadStream; void MCPWriteStream; void TransportType; void HTTPTransport; void SSETransport; void StdioTransport;",
    "void DeepMemory; void MemoryScope; void MemoryConfig; void MemoryMatch; void MemoryRecord; void ScopeInfo; void compute_composite_score; void embed_text; void embed_texts; void EncodingFlow; void EncodingState; void ItemState; void RecallFlow; void RecallState; void QdrantEdgeDefaultVectorDim; void QdrantEdgeStorage; void VECTOR_NAME; void LanceDefaultVectorDim; void LanceDBStorage; void join_scope_paths; void normalize_scope_path; void sanitize_scope_name; void DisclosureLevel; void ResourceDirName; void Skill; void ChromaDBConfig; void DEFAULT_COLLECTION; void DEFAULT_DATABASE; void DEFAULT_TENANT; void INVALID_CHARS_PATTERN; void IPV4_PATTERN; void MAX_COLLECTION_LENGTH; void MIN_COLLECTION_LENGTH; void BaseRecord; void ChromaDBClientType; void ChromaDBCollectionCreateParams; void ChromaDBCollectionSearchParams; void ChromaEmbeddingFunctionWrapper; void ExtractedSearchParams; void PreparedDocuments; void SearchResult; void DType32; void Documents; void Embeddable; void PyEmbedding; void DEFAULT_VECTOR_PARAMS; void QdrantEmbeddingFunctionWrapper; void PreparedSearchParams; void RagConfigType; void AllowedEmbeddingProviders; void EmbedderConfig; void Embedding; void ProviderSpec; void set_rag_config; void BaseClient; void BaseCollectionAddParams; void BaseCollectionParams; void BaseEmbeddingsCallable; void ClientMethodMismatchError; void OpenAIProviderSpec; void AzureProviderSpec; void BedrockProvider; void create_aws_session; void BedrockProviderSpec; void GenerativeAiProviderConfig; void VertexAIProviderConfig; void VertexAIProviderSpec; void MissingChromaDBConfig; void MissingQdrantConfig; void ChromaFactoryModule; void QdrantFactoryModule; void AzureProvider; void AzureProviderConfig; void CohereProvider; void CohereProviderConfig; void CustomEmbeddingFunction; void CustomProvider; void CustomProviderConfig; void GoogleGenAIVertexEmbeddingFunction; void GenerativeAiProvider; void HuggingFaceProvider; void HuggingFaceProviderConfig; void InstructorProvider; void InstructorProviderConfig; void JinaProvider; void JinaProviderConfig; void OllamaProvider; void OllamaProviderConfig; void ONNXProvider; void ONNXProviderConfig; void OpenAIProvider; void OpenAIProviderConfig; void OpenCLIPProvider; void OpenCLIPProviderConfig; void QdrantClient; void RoboflowProvider; void RoboflowProviderConfig; void SentenceTransformerProvider; void SentenceTransformerProviderConfig; void Text2VecProvider; void Text2VecProviderConfig; void VertexAIProvider; void VoyageAIEmbeddingFunction; void VoyageAIProvider; void VoyageAIProviderConfig; void WatsonXEmbeddingFunction; void WatsonXProvider; void WatsonXProviderConfig;",
    "void JsonProvider; void StateBaseProvider; void Auth0Provider; void BaseProvider; void ENV_VARS; void JSON_URL; void MODELS; void PROVIDERS; void check_version; void get_latest_version_from_pypi; void is_current_version_yanked; void is_newer_version_available; void ArtifactNotFoundError; void ContentTypeNegotiationError; void ERROR_MESSAGES; void JSONParseError; void NegotiatedContentTypes; void negotiate_content_types; void validate_content_type; void Action; void STANDARD_CATALOG_COMPONENTS; void A2UIMessage; void BeginRendering; void extract_a2ui_json_objects; void A2UIMessageV09; void BASIC_CATALOG_COMPONENTS; void TextV09; void extract_a2ui_v09_json_objects; void A2UIClientExtension; void A2UIConversationState; void is_v08_message; void is_v09_message; void A2UIServerExtension; void A2UI_EXTENSION_URI; void A2UI_MIME_TYPE; void A2UIValidationError; void validate_a2ui_message; void validate_catalog_components_v09; void APPLICATION_A2UI_JSON; void TEXT_PLAIN; void get_part_content_type; void RedisCacheConfig; void cancel; void cancellable; void execute; void execute_with_extensions; void list_tasks; void A2AClientConfigTypes; void A2AConfigTypes; void create_agent_response_model; void extract_a2a_agent_ids_from_config; void get_a2a_agents_and_response_model; void APIKeyServerAuth; void CoercedSecretStr; void JWTAlgorithm; void MTLSServerAuth; void OAuth2ServerAuth; void JSONFormatter; void LogContext; void configure_json_logging; void get_logger; void SigningAlgorithm; void get_key_id_from_signature; void sign_agent_card; void verify_agent_card_signature; void DelegationContext; void DelegationState; void wrap_agent_with_a2a_instance; void A2AExtension; void ConversationState; void ExtensionRegistry; void ValidatedA2AExtension; void ExtensionsMiddleware; void create_extension_registry_from_config; void get_extensions_from_config; void validate_required_extensions; void ExtensionContext; void ServerExtension; void ServerExtensionRegistry; void configure_auth_client; void parse_www_authenticate; void retry_on_401; void validate_auth_against_agent_card; void aexecute_a2a_delegation; void execute_a2a_delegation; void get_handler; void afetch_agent_card; void fetch_agent_card; void inject_a2a_server_methods; void SendMessageEvent; void TaskStateResult; void MAX_RESUBSCRIBE_ATTEMPTS; void RESUBSCRIBE_BACKOFF_BASE; void StreamingHandler; void LLMCallHookContext; void BeforeLLMCallHook; void Hook; void ReturnT; void AfterLLMCallHookMethod; void BeforeToolCallHookMethod; void BaseEventListener; void CheckpointBaseEvent; void CheckpointForkBaseEvent; void CheckpointRestoreBaseEvent; void CircularDependencyError; void Depends; void FlowEvent; void ReasoningEvent; void ToolUsageEvent; void crewaiEventBus; void crewai_event_bus; void AsyncHandler; void AsyncHandlerSet; void ExecutionPlan; void Handler; void SyncHandler; void SyncHandlerSet; void SIGNAL_EVENT_TYPES; void SignalEvent; void on_signal; void signal_event_adapter; void ENV_CONTEXT_EVENT_TYPES; void EnvContextEvent; void env_context_event_adapter; void MismatchBehavior; void handle_empty_pop; void handle_mismatch; void resume_task_scope; void AgentAggregatedEvaluationResult; void AgentEvaluationResult; void AgentEvaluator; void AggregationStrategy; void BaseEvaluator; void EvaluationScore; void EvaluationTraceCallback; void ExecutionState; void ExperimentResult; void ExperimentResults; void MetricCategory; void ParameterExtractionEvaluator; void ReasoningEfficiencyEvaluator; void ReasoningPatternType; void ToolInvocationEvaluator; void ToolSelectionEvaluator; void assert_experiment_no_regression; void assert_experiment_successfully; void create_default_evaluator; void create_evaluation_callbacks; void run_experiment; void AsyncExecutorContext; void ExecutorContext; void HumanInputProvider; void get_provider; void reset_provider; void set_provider; void ContentProcessorProvider; void NoOpContentProcessor; void get_processor; void process_content; void set_processor; void sanitizeToolName; void UsageMetrics; void SerializableCallable; void StringKnowledgeSource;",
    "void AgentResponseProtocol; void HANDLER_REGISTRY; void HandlerType; void PartsDict; void PartsMetadataDict; void PollingHandlerType; void ProtocolVersion; void PushNotificationHandlerType; void StreamingHandlerType; void Url; void BaseHandlerKwargs; void CommonParams; void PollingHandlerKwargs; void PushNotificationHandlerKwargs; void PushNotificationResultStore; void StreamingHandlerKwargs; void UpdateHandler; void extract_common_params; void PushNotificationConfig; void SignatureInput; void WebhookSignatureConfig; void WebhookSignatureMode; void NegotiationSource; void TransportProtocol; void build_a2ui_system_prompt; void build_a2ui_v09_system_prompt; void CrewAIEventsBus; void EventListener; void HandlerGraph; void build_execution_plan; void is_async_handler; void is_call_handler_safe; void TraceBatch; void TraceBatchManager; void get_user_id; void is_first_execution; void is_tracing_enabled_in_context; void mark_first_execution_completed; void reset_tracing_enabled; void safe_serialize_to_dict; void set_suppress_tracing_messages; void set_tracing_enabled; void should_enable_tracing; void truncate_messages; void BG_CARD; void BG_DARK; void BORDER_SUBTLE; void CREWAI_ORANGE; void CSSExtension; void DARK_GRAY; void GRAY; void JSExtension; void TEXT_PRIMARY; void TEXT_SECONDARY; void WHITE; void calculate_node_positions; void render_interactive; void NodeMetadata; void StructureEdge; void BaseInterceptor; void HookU; void AsyncHTTPTransport; void HTTPTransportKwargs;",
    "void BaseTool; void CrewStructuredTool; void EnvVar; void toolDecorator; void Memory; void CheckpointConfig; void CheckpointEventType; void apply_checkpoint; void FlowMethodData; void FlowExecutionData; void PendingListenerKey; void AND_CONDITION; void OR_CONDITION; void FlowMethod; void StartMethod; void FlowConditionType; void dfs_ancestors; void is_ancestor; void is_flow_condition_dict; void is_flow_condition_list; void is_flow_method; void is_flow_method_callable; void is_flow_method_name; void is_simple_flow_condition; void process_router_paths; void build_task_prompt_with_schema; void prepare_tools; void TaskExecutionData; void setup_agents;",
    "console.log(Boolean(Agent), Boolean(Crew), Boolean(Task), Boolean(LLM), __version__, Process.sequential);",
    "",
  ].join("\n"));
  writeFileSync(join(appDir, "index.ts"), [
    "import { Agent, Crew, LLM, Process, Task, __version__ } from '@crewai-ts/core';",
    "import { CrewBase, agent, before_kickoff, crew, task } from '@crewai-ts/core/project';",
    "import { Flow, start } from '@crewai-ts/core/flow';",
    "import { ConsoleProvider as FlowConsoleProvider, FlowStructure as FlowStructureMarker, HumanFeedbackProvider as HumanFeedbackProviderMarker, HumanFeedbackResult as HumanFeedbackResultMarker, InputProvider as InputProviderMarker, InputResponse as InputResponseMarker, PendingFeedbackContext as PendingFeedbackContextMarker, flow_config, visualize_flow_structure } from '@crewai-ts/core/flow';",
    "import { F as FlowRuntimeF, FlowMeta, LockedDictProxy, LockedListProxy, StateProxy } from '@crewai-ts/core/flow/flow';",
    "import { DistilledLessons, F as HumanFeedbackF, HumanFeedbackConfig as HumanFeedbackConfigMarker, HumanFeedbackMethod, HumanFeedbackMethod as HumanFeedbackMethodMarker, PreReviewResult } from '@crewai-ts/core/flow/human_feedback';",
    "import { EdgeInfo, FlowStructureInfo, MethodInfo, StateFieldInfo, StateSchemaInfo } from '@crewai-ts/core/flow/flow_serializer';",
    "import { JsonFlowPersistence, persist } from '@crewai-ts/core/flow/persistence';",
    "import { SQLiteFlowPersistence } from '@crewai-ts/core/flow/persistence/sqlite';",
    "import type { InputProvider } from '@crewai-ts/core/flow/input_provider';",
    "import { CrewBase as DeepCrewBase } from '@crewai-ts/core/project/crew_base';",
    "import { AgentConfig as CrewBaseAgentConfig, CrewBaseMeta, CallableT, close_mcp_server, get_mcp_tools, load_configurations, load_yaml, map_all_agent_variables, map_all_task_variables } from '@crewai-ts/core/project/crew_base';",
    "import { agent as deepAgent } from '@crewai-ts/core/project/annotations';",
    "import { P as AnnotationP, P2, R as AnnotationR, R2, SelfT, T as AnnotationT } from '@crewai-ts/core/project/annotations';",
    "import { DecoratedMethod, AgentMethod, TaskMethod, CrewMetadata, CrewInstance, CrewClass, OutputJsonClass, OutputPydanticClass } from '@crewai-ts/core/project/wrappers';",
    "import { memoize } from '@crewai-ts/core/project/utils';",
    "import { TaskOutput } from '@crewai-ts/core/tasks/task_output';",
    "import { OutputFormat } from '@crewai-ts/core/tasks/output_format';",
    "import { ConditionalTask } from '@crewai-ts/core/tasks/conditional_task';",
    "import { LLMGuardrail } from '@crewai-ts/core/tasks/llm_guardrail';",
    "import { HallucinationGuardrail } from '@crewai-ts/core/tasks/hallucination_guardrail';",
    "import { LLM as SubpathLLM, ANTHROPIC_PREFIXES, AccumulatedToolArgs, Delta, FunctionArgs, MAX_CONTEXT, MIN_CONTEXT, StreamingChoices } from '@crewai-ts/core/llm';",
    "import { AnthropicModels, AzureModels, BedrockModels, GeminiModels, OpenAIModels } from '@crewai-ts/core/llms/constants';",
    "import { extract_tool_info, log_tool_conversion, safe_tool_conversion, sanitize_function_name, validate_function_name } from '@crewai-ts/core/llms/providers/utils/common';",
    "import { Crew as SingularCrew } from '@crewai-ts/core/crew';",
    "import { Task as SingularTask } from '@crewai-ts/core/task';",
    "import { BaseTool, CrewStructuredTool, EnvVar, tool as toolDecorator } from '@crewai-ts/core/tools';",
    "import { BaseTool as DeepBaseTool } from '@crewai-ts/core/tools/base_tool';",
    "import { CrewStructuredTool as DeepStructuredTool } from '@crewai-ts/core/tools/structured_tool';",
    "import { AddImageTool } from '@crewai-ts/core/tools/agent_tools/add_image_tool';",
    "import { AgentTools } from '@crewai-ts/core/tools/agent_tools/agent_tools';",
    "import { AskQuestionTool } from '@crewai-ts/core/tools/agent_tools/ask_question_tool';",
    "import { BaseAgentTool } from '@crewai-ts/core/tools/agent_tools/base_agent_tools';",
    "import { DelegateWorkTool } from '@crewai-ts/core/tools/agent_tools/delegate_work_tool';",
    "import { ReadFileTool } from '@crewai-ts/core/tools/agent_tools/read_file_tool';",
    "import { CacheTools } from '@crewai-ts/core/tools/cache_tools/cache_tools';",
    "import { MCPNativeTool } from '@crewai-ts/core/tools/mcp_native_tool';",
    "import { MCPToolWrapper } from '@crewai-ts/core/tools/mcp_tool_wrapper';",
    "import { ToolCalling } from '@crewai-ts/core/tools/tool_calling';",
    "import { ToolResult } from '@crewai-ts/core/tools/tool_types';",
    "import { ToolUsage } from '@crewai-ts/core/tools/tool_usage';",
    "import { RecallMemoryTool, RememberTool, create_memory_tools } from '@crewai-ts/core/tools/memory_tools';",
    "import { Telemetry } from '@crewai-ts/core/telemetry/telemetry';",
    "import { CREWAI_TELEMETRY_BASE_URL } from '@crewai-ts/core/telemetry/constants';",
    "import { close_span } from '@crewai-ts/core/telemetry/utils';",
    "import { PlanStep, TodoList } from '@crewai-ts/core/utilities/planning_types';",
    "import { MIN_REQUIRED_VERSION, chat_loop, flush_input, get_user_input, handle_user_input, initialize_chat_llm, load_crew_and_name, run_chat, show_loading } from '@crewai-ts/core/utilities/crew_chat';",
    "import { PlanPerTask, PlannerTaskPydanticOutput } from '@crewai-ts/core/utilities/planning_handler';",
    "import { AgentReasoning, FUNCTION_SCHEMA } from '@crewai-ts/core/utilities/reasoning_handler';",
    "import { NOT_SPECIFIED } from '@crewai-ts/core/utilities/constants';",
    "import { GuardrailCallable, GuardrailType, GuardrailsType } from '@crewai-ts/core/utilities/guardrail_types';",
    "import { ImportedDefinition, adapter, require as requireOptionalDependency } from '@crewai-ts/core/utilities/import_utils';",
    "import { ColoredText, PrinterColor } from '@crewai-ts/core/utilities/printer';",
    "import { Serializable, SerializablePrimitive } from '@crewai-ts/core/utilities/serialization';",
    "import { ENV_VARS, JSON_URL, MODELS, PROVIDERS } from '@crewai-ts/core/constants';",
    "import { check_version, get_latest_version_from_pypi, is_current_version_yanked, is_newer_version_available } from '@crewai-ts/core/version';",
    "import { RPMController } from '@crewai-ts/core/utilities/rpm_controller';",
    "import { JsonSchemaInfo, create_model_from_schema } from '@crewai-ts/core/utilities/pydantic_schema_utils';",
    "import { CreateConverterKwargs, create_converter } from '@crewai-ts/core/utilities/converter';",
    "import { StepExecutionContext, StepResult } from '@crewai-ts/core/utilities/step_execution_context';",
    "import { StreamingState, TaskInfo, create_async_chunk_generator, create_chunk_generator, create_streaming_state, logger as streamingLogger, register_cleanup, signal_end, signal_error } from '@crewai-ts/core/utilities/streaming';",
    "import { LLMMessage } from '@crewai-ts/core/utilities/types';",
    "import { ACTION_INPUT_ONLY_REGEX, ACTION_INPUT_REGEX, ACTION_REGEX } from '@crewai-ts/core/agents/constants';",
    "import { BaseAgent, PlatformApp, PlatformAppOrAction } from '@crewai-ts/core/agents/agent_builder/base_agent';",
    "import { BaseAgentExecutor } from '@crewai-ts/core/agents/agent_builder/base_agent_executor';",
    "import { AgentExecutor, AgentExecutorState, CrewAgentExecutorFlow } from '@crewai-ts/core/experimental/agent_executor';",
    "import { OutputConverter } from '@crewai-ts/core/agents/agent_builder/utilities/base_output_converter';",
    "import { TokenProcess } from '@crewai-ts/core/agents/agent_builder/utilities/base_token_process';",
    "import { CrewAgentExecutor } from '@crewai-ts/core/agents/crew_agent_executor';",
    "import { PlannerObserver } from '@crewai-ts/core/agents/planner_observer';",
    "import { StepExecutor } from '@crewai-ts/core/agents/step_executor';",
    "import { SummaryContent, NativeToolCallResult, aget_llm_response, build_tool_calls_assistant_message, check_native_tool_support, enforce_rpm_limit, execute_single_native_tool_call, extract_tool_call_info, format_answer, get_llm_response, handle_agent_action_core, handle_context_length, handle_max_iterations_exceeded, handle_output_parser_exception, handle_unknown_error, is_context_length_exceeded, is_inside_event_loop, is_tool_call_list, load_agent_from_repository, parse_tool_call_args, parse_tools, process_llm_response, setup_native_tools, show_agent_logs, summarize_messages, track_delegation_if_needed } from '@crewai-ts/core/utilities/agent_utils';",
    "import { extract_available_exports, extract_tools_metadata, fetch_crews, get_crew_instance, get_crews, get_flow_instance, get_flows, is_valid_tool } from '@crewai-ts/core/utilities/project_utils';",
    "import { BaseAgentAdapter } from '@crewai-ts/core/agents/agent_adapters/base_agent_adapter';",
    "import { BaseToolAdapter } from '@crewai-ts/core/agents/agent_adapters/base_tool_adapter';",
    "import { BaseConverterAdapter } from '@crewai-ts/core/agents/agent_adapters/base_converter_adapter';",
    "import { OpenAIAgentAdapter, Runner } from '@crewai-ts/core/agents/agent_adapters/openai_agents/openai_adapter';",
    "import { OpenAIAgentToolAdapter } from '@crewai-ts/core/agents/agent_adapters/openai_agents/openai_agent_tool_adapter';",
    "import { OpenAIConverterAdapter } from '@crewai-ts/core/agents/agent_adapters/openai_agents/structured_output_converter';",
    "import { OpenAITool } from '@crewai-ts/core/agents/agent_adapters/openai_agents/protocols';",
    "import { LangGraphAgentAdapter } from '@crewai-ts/core/agents/agent_adapters/langgraph/langgraph_adapter';",
    "import { LangGraphToolAdapter } from '@crewai-ts/core/agents/agent_adapters/langgraph/langgraph_tool_adapter';",
    "import { LangGraphConverterAdapter } from '@crewai-ts/core/agents/agent_adapters/langgraph/structured_output_converter';",
    "import { LangGraphPrebuiltModule } from '@crewai-ts/core/agents/agent_adapters/langgraph/protocols';",
    "import { CodeInterpreterFileResult, CodeInterpreterLogResult, CodeInterpreterResult, ComputerUseResult, FileSearchResult, FileSearchResultItem, OpenAICompletion, ReasoningSummary, ResponsesAPIResult, WebSearchResult } from '@crewai-ts/core/llms/providers/openai/completion';",
    "import { OPENAI_COMPATIBLE_PROVIDERS, OpenAICompatibleCompletion, ProviderConfig } from '@crewai-ts/core/llms/providers/openai_compatible/completion';",
    "import { ANTHROPIC_FILES_API_BETA, ANTHROPIC_STRUCTURED_OUTPUTS_BETA, AnthropicCompletion, AnthropicThinkingConfig, AnthropicToolSearchConfig, NATIVE_STRUCTURED_OUTPUT_MODELS, TOOL_SEARCH_TOOL_TYPES } from '@crewai-ts/core/llms/providers/anthropic/completion';",
    "import { AzureCompletion, AzureCompletionParams } from '@crewai-ts/core/llms/providers/azure/completion';",
    "import { BedrockCompletion, BedrockConverseRequestBody, BedrockConverseStreamRequestBody, ConverseToolTypeDef, STRUCTURED_OUTPUT_TOOL_NAME, ToolInputSchema, ToolSpec } from '@crewai-ts/core/llms/providers/bedrock/completion';",
    "import { MCPToolResolver } from '@crewai-ts/core/mcp/tool_resolver';",
    "import { MCPClient } from '@crewai-ts/core/mcp/client';",
    "import { MCPServerConfig, MCPServerStdio, MCPServerHTTP, MCPServerSSE } from '@crewai-ts/core/mcp/config';",
    "import { StaticToolFilter, ToolFilter, ToolFilterContext } from '@crewai-ts/core/mcp/filters';",
    "import { BaseTransport, MCPReadStream, MCPWriteStream, TransportType } from '@crewai-ts/core/mcp/transports/base';",
    "import { HTTPTransport } from '@crewai-ts/core/mcp/transports/http';",
    "import { SSETransport } from '@crewai-ts/core/mcp/transports/sse';",
    "import { StdioTransport } from '@crewai-ts/core/mcp/transports/stdio';",
    "import { Memory } from '@crewai-ts/core/memory';",
    "import { Memory as DeepMemory } from '@crewai-ts/core/memory/unified_memory';",
    "import { MemoryScope } from '@crewai-ts/core/memory/memory_scope';",
    "import { MemoryConfig, MemoryMatch, MemoryRecord, ScopeInfo, compute_composite_score, embed_text, embed_texts } from '@crewai-ts/core/memory/types';",
    "import { EncodingFlow, EncodingState, ItemState } from '@crewai-ts/core/memory/encoding_flow';",
    "import { RecallFlow, RecallState } from '@crewai-ts/core/memory/recall_flow';",
    "import { DEFAULT_VECTOR_DIM as QdrantEdgeDefaultVectorDim, QdrantEdgeStorage, VECTOR_NAME } from '@crewai-ts/core/memory/storage/qdrant_edge_storage';",
    "import { DEFAULT_VECTOR_DIM as LanceDefaultVectorDim, LanceDBStorage } from '@crewai-ts/core/memory/storage/lancedb_storage';",
    "import { join_scope_paths, normalize_scope_path, sanitize_scope_name } from '@crewai-ts/core/memory/utils';",
    "import { DisclosureLevel, ResourceDirName, Skill } from '@crewai-ts/core/skills/models';",
    "import { ChromaDBConfig } from '@crewai-ts/core/rag/chromadb/config';",
    "import { DEFAULT_COLLECTION, DEFAULT_DATABASE, DEFAULT_TENANT, INVALID_CHARS_PATTERN, IPV4_PATTERN, MAX_COLLECTION_LENGTH, MIN_COLLECTION_LENGTH } from '@crewai-ts/core/rag/chromadb/constants';",
    "import { BaseRecord } from '@crewai-ts/core/rag/chromadb/types';",
    "import { ChromaDBClientType, ChromaDBCollectionCreateParams, ChromaDBCollectionSearchParams, ChromaEmbeddingFunctionWrapper, ExtractedSearchParams, PreparedDocuments } from '@crewai-ts/core/rag/chromadb/types';",
    "import { SearchResult } from '@crewai-ts/core/rag/core/types';",
    "import { DType32, Documents, Embeddable, PyEmbedding } from '@crewai-ts/core/rag/core/types';",
    "import { DEFAULT_VECTOR_PARAMS } from '@crewai-ts/core/rag/qdrant/constants';",
    "import { QdrantEmbeddingFunctionWrapper, PreparedSearchParams } from '@crewai-ts/core/rag/qdrant/types';",
    "import { RagConfigType } from '@crewai-ts/core/rag/config/types';",
    "import { AllowedEmbeddingProviders, EmbedderConfig, Embedding, ProviderSpec } from '@crewai-ts/core/rag/embeddings/types';",
    "import { set_rag_config } from '@crewai-ts/core/rag/config/utils';",
    "import { BaseClient, BaseCollectionAddParams, BaseCollectionParams } from '@crewai-ts/core/rag/core/base_client';",
    "import { BaseEmbeddingsCallable } from '@crewai-ts/core/rag/core/base_embeddings_callable';",
    "import { ClientMethodMismatchError } from '@crewai-ts/core/rag/core/exceptions';",
    "import { OpenAIProviderSpec } from '@crewai-ts/core/rag/embeddings/providers/openai/types';",
    "import { AzureProviderSpec } from '@crewai-ts/core/rag/embeddings/providers/microsoft/types';",
    "import { BedrockProviderSpec } from '@crewai-ts/core/rag/embeddings/providers/aws/types';",
    "import { GenerativeAiProviderConfig, VertexAIProviderConfig, VertexAIProviderSpec } from '@crewai-ts/core/rag/embeddings/providers/google/types';",
    "import { MissingChromaDBConfig, MissingQdrantConfig } from '@crewai-ts/core/rag/config/optional_imports/providers';",
    "import { ChromaFactoryModule, QdrantFactoryModule } from '@crewai-ts/core/rag/config/optional_imports/protocols';",
    "import { AzureProvider, AzureProviderConfig, CohereProvider, CohereProviderConfig, CustomEmbeddingFunction, CustomProvider, CustomProviderConfig, GoogleGenAIVertexEmbeddingFunction, GenerativeAiProvider, HuggingFaceProvider, HuggingFaceProviderConfig, InstructorProvider, InstructorProviderConfig, JinaProvider, JinaProviderConfig, OllamaProvider, OllamaProviderConfig, ONNXProvider, ONNXProviderConfig, OpenAIProvider, OpenAIProviderConfig, OpenCLIPProvider, OpenCLIPProviderConfig, QdrantClient, RoboflowProvider, RoboflowProviderConfig, SentenceTransformerProvider, SentenceTransformerProviderConfig, Text2VecProvider, Text2VecProviderConfig, VertexAIProvider, VoyageAIEmbeddingFunction, VoyageAIProvider, VoyageAIProviderConfig, WatsonXEmbeddingFunction, WatsonXProvider, WatsonXProviderConfig } from '@crewai-ts/core/rag/embeddings/providers/openai/openai_provider';",
    "import { BedrockProvider, create_aws_session } from '@crewai-ts/core/rag/embeddings/providers/aws/bedrock';",
    "import { JsonProvider } from '@crewai-ts/core/state/provider/json_provider';",
    "import { BaseProvider as StateBaseProvider } from '@crewai-ts/core/state/provider/core';",
    "import { Auth0Provider } from '@crewai-ts/core/auth/providers/auth0';",
    "import { BaseProvider } from '@crewai-ts/core/auth/providers/base_provider';",
    "import { ArtifactNotFoundError, ContentTypeNegotiationError, ERROR_MESSAGES, JSONParseError, NegotiatedContentTypes, negotiate_content_types, validate_content_type } from '@crewai-ts/core/a2a/errors';",
    "import { Action, STANDARD_CATALOG_COMPONENTS } from '@crewai-ts/core/a2a/extensions/a2ui/catalog';",
    "import { A2UIMessage, BeginRendering, extract_a2ui_json_objects } from '@crewai-ts/core/a2a/extensions/a2ui/models';",
    "import { A2UIMessageV09, BASIC_CATALOG_COMPONENTS, TextV09, extract_a2ui_v09_json_objects } from '@crewai-ts/core/a2a/extensions/a2ui/v0_9';",
    "import { A2UIClientExtension, A2UIConversationState, is_v08_message, is_v09_message } from '@crewai-ts/core/a2a/extensions/a2ui/client_extension';",
    "import { A2UIServerExtension, A2UI_EXTENSION_URI, A2UI_MIME_TYPE } from '@crewai-ts/core/a2a/extensions/a2ui/server_extension';",
    "import { A2UIValidationError, validate_a2ui_message, validate_catalog_components_v09 } from '@crewai-ts/core/a2a/extensions/a2ui/validator';",
    "import { APPLICATION_A2UI_JSON, TEXT_PLAIN, get_part_content_type } from '@crewai-ts/core/a2a/utils/content_type';",
    "import { RedisCacheConfig, cancel, cancellable, execute, execute_with_extensions, list_tasks } from '@crewai-ts/core/a2a/utils/task';",
    "import { A2AClientConfigTypes, A2AConfigTypes, create_agent_response_model, extract_a2a_agent_ids_from_config, get_a2a_agents_and_response_model } from '@crewai-ts/core/a2a/utils/response_model';",
    "import { APIKeyServerAuth, CoercedSecretStr, JWTAlgorithm, MTLSServerAuth, OAuth2ServerAuth } from '@crewai-ts/core/a2a/auth/server_schemes';",
    "import { JSONFormatter, LogContext, configure_json_logging, get_logger } from '@crewai-ts/core/a2a/utils/logging';",
    "import { SigningAlgorithm, get_key_id_from_signature, sign_agent_card, verify_agent_card_signature } from '@crewai-ts/core/a2a/utils/agent_card_signing';",
    "import { DelegationContext, DelegationState, wrap_agent_with_a2a_instance } from '@crewai-ts/core/a2a/wrapper';",
    "import { A2AExtension, ConversationState, ExtensionRegistry, ValidatedA2AExtension } from '@crewai-ts/core/a2a/extensions/base';",
    "import { ExtensionsMiddleware, create_extension_registry_from_config, get_extensions_from_config, validate_required_extensions } from '@crewai-ts/core/a2a/extensions/registry';",
    "import { ExtensionContext, ServerExtension, ServerExtensionRegistry } from '@crewai-ts/core/a2a/extensions/server';",
    "import { configure_auth_client, parse_www_authenticate, retry_on_401, validate_auth_against_agent_card } from '@crewai-ts/core/a2a/auth/utils';",
    "import { aexecute_a2a_delegation, execute_a2a_delegation, get_handler } from '@crewai-ts/core/a2a/utils/delegation';",
    "import { afetch_agent_card, fetch_agent_card, inject_a2a_server_methods } from '@crewai-ts/core/a2a/utils/agent_card';",
    "import { SendMessageEvent, TaskStateResult } from '@crewai-ts/core/a2a/task_helpers';",
    "import { MAX_RESUBSCRIBE_ATTEMPTS, RESUBSCRIBE_BACKOFF_BASE, StreamingHandler } from '@crewai-ts/core/a2a/updates/streaming/handler';",
    "import { PushNotificationConfig, SignatureInput } from '@crewai-ts/core/a2a/updates/push_notifications/config';",
    "import { WebhookSignatureConfig, WebhookSignatureMode } from '@crewai-ts/core/a2a/updates/push_notifications/signature';",
    "import { NegotiationSource, TransportProtocol } from '@crewai-ts/core/a2a/utils/transport';",
    "import { build_a2ui_system_prompt, build_a2ui_v09_system_prompt } from '@crewai-ts/core/a2a/extensions/a2ui/prompt';",
    "import { AgentResponseProtocol, HANDLER_REGISTRY, HandlerType, PartsDict, PartsMetadataDict, PollingHandlerType, ProtocolVersion, PushNotificationHandlerType, StreamingHandlerType, Url } from '@crewai-ts/core/a2a/types';",
    "import { BaseHandlerKwargs, CommonParams, PollingHandlerKwargs, PushNotificationHandlerKwargs, PushNotificationResultStore, StreamingHandlerKwargs, UpdateHandler, extract_common_params } from '@crewai-ts/core/a2a/updates/base';",
    "import { get_user_id, is_first_execution, is_tracing_enabled_in_context, mark_first_execution_completed, reset_tracing_enabled, safe_serialize_to_dict, set_suppress_tracing_messages, set_tracing_enabled, should_enable_tracing, truncate_messages } from '@crewai-ts/core/events/listeners/tracing/utils';",
    "import { BG_CARD, BG_DARK, BORDER_SUBTLE, CREWAI_ORANGE, CSSExtension, DARK_GRAY, GRAY, JSExtension, TEXT_PRIMARY, TEXT_SECONDARY, WHITE, calculate_node_positions, render_interactive } from '@crewai-ts/core/flow/visualization/renderers/interactive';",
    "import { NodeMetadata, StructureEdge } from '@crewai-ts/core/flow/visualization/types';",
    "import { LLMCallHookContext } from '@crewai-ts/core/hooks/llm_hooks';",
    "import { BeforeLLMCallHook, Hook, ReturnT } from '@crewai-ts/core/hooks/types';",
    "import { BaseInterceptor, U as HookU } from '@crewai-ts/core/llms/hooks/base';",
    "import { AsyncHTTPTransport, HTTPTransportKwargs } from '@crewai-ts/core/llms/hooks/transport';",
    "import { AfterLLMCallHookMethod, BeforeToolCallHookMethod } from '@crewai-ts/core/hooks/wrappers';",
    "import { BaseEventListener, CheckpointBaseEvent, CheckpointForkBaseEvent, CheckpointRestoreBaseEvent, CircularDependencyError, CrewAIEventsBus, Depends, EventListener, FlowEvent, HandlerGraph, ReasoningEvent, ToolUsageEvent, build_execution_plan, crewaiEventBus, crewai_event_bus } from '@crewai-ts/core/events/event_bus';",
    "import { is_async_handler, is_call_handler_safe } from '@crewai-ts/core/events/utils/handlers';",
    "import { TraceBatch, TraceBatchManager } from '@crewai-ts/core/events/listeners/tracing/trace_batch_manager';",
    "import { AsyncHandler, AsyncHandlerSet, ExecutionPlan, Handler, SyncHandler, SyncHandlerSet } from '@crewai-ts/core/events/types/event_bus_types';",
    "import { SIGNAL_EVENT_TYPES, SignalEvent, on_signal, signal_event_adapter } from '@crewai-ts/core/events/types/system_events';",
    "import { ENV_CONTEXT_EVENT_TYPES, EnvContextEvent, env_context_event_adapter } from '@crewai-ts/core/events/types/env_events';",
    "import { MismatchBehavior, handle_empty_pop, handle_mismatch, resume_task_scope } from '@crewai-ts/core/events/event_context';",
    "import { AgentAggregatedEvaluationResult, AgentEvaluationResult, AggregationStrategy, BaseEvaluator, EvaluationScore, MetricCategory } from '@crewai-ts/core/experimental/evaluation/base_evaluator';",
    "import { AgentEvaluator, ExecutionState, create_default_evaluator } from '@crewai-ts/core/experimental/evaluation/agent_evaluator';",
    "import { ParameterExtractionEvaluator, ToolInvocationEvaluator, ToolSelectionEvaluator } from '@crewai-ts/core/experimental/evaluation/metrics/tools_metrics';",
    "import { ReasoningEfficiencyEvaluator, ReasoningPatternType } from '@crewai-ts/core/experimental/evaluation/metrics/reasoning_metrics';",
    "import { ExperimentResult, ExperimentResults } from '@crewai-ts/core/experimental/evaluation/experiment/result';",
    "import { EvaluationTraceCallback, create_evaluation_callbacks } from '@crewai-ts/core/experimental/evaluation/evaluation_listener';",
    "import { assert_experiment_no_regression, assert_experiment_successfully, run_experiment } from '@crewai-ts/core/experimental/evaluation/testing';",
    "import { AsyncExecutorContext, ExecutorContext, HumanInputProvider, get_provider, reset_provider, set_provider } from '@crewai-ts/core/core/providers/human_input';",
    "import { ContentProcessorProvider, NoOpContentProcessor, get_processor, process_content, set_processor } from '@crewai-ts/core/core/providers/content_processor';",
    "import { sanitizeToolName } from '@crewai-ts/core/utilities/string_utils';",
    "import { UsageMetrics } from '@crewai-ts/core/types/usage_metrics';",
    "import { SerializableCallable } from '@crewai-ts/core/types/callback';",
    "import { StringKnowledgeSource } from '@crewai-ts/core/knowledge/source/string_knowledge_source';",
    "import { CheckpointConfig } from '@crewai-ts/core/state';",
    "import { CheckpointEventType, apply_checkpoint } from '@crewai-ts/core/state/checkpoint_config';",
    "import { FlowMethodData, FlowExecutionData, PendingListenerKey } from '@crewai-ts/core/flow/types';",
    "import { AND_CONDITION, OR_CONDITION } from '@crewai-ts/core/flow/constants';",
    "import { FlowMethod, StartMethod, FlowConditionType } from '@crewai-ts/core/flow/flow_wrappers';",
    "import { dfs_ancestors, is_ancestor, is_flow_condition_dict, is_flow_condition_list, is_flow_method, is_flow_method_callable, is_flow_method_name, is_simple_flow_condition, process_router_paths } from '@crewai-ts/core/flow/utils';",
    "import { build_task_prompt_with_schema, prepare_tools } from '@crewai-ts/core/agent/utils';",
    "import { TaskExecutionData, setup_agents } from '@crewai-ts/core/crews/utils';",
    "",
    "const researchAgent = new Agent({",
    "  role: 'Researcher',",
    "  goal: 'Find facts',",
    "  backstory: 'Careful analyst',",
    "  llm: () => 'done',",
    "});",
    "const researchTask = new Task({ description: 'Research', expected_output: 'A brief', agent: researchAgent });",
    "const researchCrew = new Crew({ agents: [researchAgent], tasks: [researchTask], process: Process.sequential });",
    "const llm = new LLM({ model: 'gpt-4o-mini' });",
    "void __version__;",
    "void llm;",
    "void researchCrew;",
    "void CrewBase; void agent; void before_kickoff; void task;",
    "void Flow; void start; void FlowConsoleProvider; void FlowStructureMarker; void HumanFeedbackProviderMarker; void HumanFeedbackResultMarker; void InputProviderMarker; void InputResponseMarker; void PendingFeedbackContextMarker; void flow_config; void visualize_flow_structure; void FlowRuntimeF; void FlowMeta; void LockedDictProxy; void LockedListProxy; void StateProxy; void DistilledLessons; void HumanFeedbackF; void HumanFeedbackConfigMarker; void HumanFeedbackMethod; void HumanFeedbackMethodMarker; void PreReviewResult; void EdgeInfo; void FlowStructureInfo; void MethodInfo; void StateFieldInfo; void StateSchemaInfo; void JsonFlowPersistence; void persist; void SubpathLLM; void ANTHROPIC_PREFIXES; void AccumulatedToolArgs; void Delta; void FunctionArgs; void MAX_CONTEXT; void MIN_CONTEXT; void StreamingChoices; void AnthropicModels; void AzureModels; void BedrockModels; void GeminiModels; void OpenAIModels; void extract_tool_info; void log_tool_conversion; void safe_tool_conversion; void sanitize_function_name; void validate_function_name; void SingularCrew; void SingularTask;",
    "void SQLiteFlowPersistence; void (null as InputProvider | null); void DeepCrewBase; void CrewBaseAgentConfig; void CrewBaseMeta; void CallableT; void close_mcp_server; void get_mcp_tools; void load_configurations; void load_yaml; void map_all_agent_variables; void map_all_task_variables; void deepAgent; void AnnotationP; void P2; void AnnotationR; void R2; void SelfT; void AnnotationT; void DecoratedMethod; void AgentMethod; void TaskMethod; void CrewMetadata; void CrewInstance; void CrewClass; void OutputJsonClass; void OutputPydanticClass; void memoize; void TaskOutput; void OutputFormat; void ConditionalTask; void LLMGuardrail; void HallucinationGuardrail;",
    "void DeepBaseTool; void DeepStructuredTool; void AddImageTool; void AgentTools; void AskQuestionTool; void BaseAgentTool; void DelegateWorkTool; void ReadFileTool; void CacheTools; void MCPNativeTool; void MCPToolWrapper; void ToolCalling; void ToolResult; void ToolUsage; void RecallMemoryTool; void RememberTool; void create_memory_tools; void Telemetry; void CREWAI_TELEMETRY_BASE_URL; void close_span; void PlanStep; void TodoList; void MIN_REQUIRED_VERSION; void chat_loop; void flush_input; void get_user_input; void handle_user_input; void initialize_chat_llm; void load_crew_and_name; void run_chat; void show_loading; void PlanPerTask; void PlannerTaskPydanticOutput; void AgentReasoning; void FUNCTION_SCHEMA; void NOT_SPECIFIED; void GuardrailCallable; void GuardrailType; void GuardrailsType; void ImportedDefinition; void adapter; void requireOptionalDependency; void ColoredText; void PrinterColor; void Serializable; void SerializablePrimitive; void RPMController; void JsonSchemaInfo; void create_model_from_schema; void CreateConverterKwargs; void create_converter; void StepExecutionContext; void StepResult; void StreamingState; void TaskInfo; void create_async_chunk_generator; void create_chunk_generator; void create_streaming_state; void streamingLogger; void register_cleanup; void signal_end; void signal_error; void LLMMessage; void ACTION_INPUT_ONLY_REGEX; void ACTION_INPUT_REGEX; void ACTION_REGEX; void BaseAgent; void PlatformApp; void PlatformAppOrAction; void BaseAgentExecutor; void AgentExecutor; void AgentExecutorState; void CrewAgentExecutorFlow; void OutputConverter; void TokenProcess; void CrewAgentExecutor; void PlannerObserver; void StepExecutor; void SummaryContent; void NativeToolCallResult; void aget_llm_response; void build_tool_calls_assistant_message; void check_native_tool_support; void enforce_rpm_limit; void execute_single_native_tool_call; void extract_tool_call_info; void format_answer; void get_llm_response; void handle_agent_action_core; void handle_context_length; void handle_max_iterations_exceeded; void handle_output_parser_exception; void handle_unknown_error; void is_context_length_exceeded; void is_inside_event_loop; void is_tool_call_list; void load_agent_from_repository; void parse_tool_call_args; void parse_tools; void process_llm_response; void setup_native_tools; void show_agent_logs; void summarize_messages; void track_delegation_if_needed; void extract_available_exports; void extract_tools_metadata; void fetch_crews; void get_crew_instance; void get_crews; void get_flow_instance; void get_flows; void is_valid_tool; void BaseAgentAdapter; void BaseToolAdapter; void BaseConverterAdapter; void OpenAIAgentAdapter; void Runner; void OpenAIAgentToolAdapter; void OpenAIConverterAdapter; void OpenAITool; void LangGraphAgentAdapter; void LangGraphToolAdapter; void LangGraphConverterAdapter; void LangGraphPrebuiltModule;",
    "void CodeInterpreterFileResult; void CodeInterpreterLogResult; void CodeInterpreterResult; void ComputerUseResult; void FileSearchResult; void FileSearchResultItem; void OpenAICompletion; void ReasoningSummary; void ResponsesAPIResult; void WebSearchResult; void OPENAI_COMPATIBLE_PROVIDERS; void OpenAICompatibleCompletion; void ProviderConfig; void ANTHROPIC_FILES_API_BETA; void ANTHROPIC_STRUCTURED_OUTPUTS_BETA; void AnthropicCompletion; void AnthropicThinkingConfig; void AnthropicToolSearchConfig; void NATIVE_STRUCTURED_OUTPUT_MODELS; void TOOL_SEARCH_TOOL_TYPES; void AzureCompletion; void AzureCompletionParams; void BedrockCompletion; void BedrockConverseRequestBody; void BedrockConverseStreamRequestBody; void ConverseToolTypeDef; void STRUCTURED_OUTPUT_TOOL_NAME; void ToolInputSchema; void ToolSpec;",
    "void MCPToolResolver; void MCPClient; void MCPServerConfig; void MCPServerStdio; void MCPServerHTTP; void MCPServerSSE; void StaticToolFilter; void ToolFilter; void ToolFilterContext; void BaseTransport; void MCPReadStream; void MCPWriteStream; void TransportType; void HTTPTransport; void SSETransport; void StdioTransport;",
    "void DeepMemory; void MemoryScope; void MemoryConfig; void MemoryMatch; void MemoryRecord; void ScopeInfo; void compute_composite_score; void embed_text; void embed_texts; void EncodingFlow; void EncodingState; void ItemState; void RecallFlow; void RecallState; void QdrantEdgeDefaultVectorDim; void QdrantEdgeStorage; void VECTOR_NAME; void LanceDefaultVectorDim; void LanceDBStorage; void join_scope_paths; void normalize_scope_path; void sanitize_scope_name; void DisclosureLevel; void ResourceDirName; void Skill; void ChromaDBConfig; void DEFAULT_COLLECTION; void DEFAULT_DATABASE; void DEFAULT_TENANT; void INVALID_CHARS_PATTERN; void IPV4_PATTERN; void MAX_COLLECTION_LENGTH; void MIN_COLLECTION_LENGTH; void BaseRecord; void ChromaDBClientType; void ChromaDBCollectionCreateParams; void ChromaDBCollectionSearchParams; void ChromaEmbeddingFunctionWrapper; void ExtractedSearchParams; void PreparedDocuments; void SearchResult; void DType32; void Documents; void Embeddable; void PyEmbedding; void DEFAULT_VECTOR_PARAMS; void QdrantEmbeddingFunctionWrapper; void PreparedSearchParams; void RagConfigType; void AllowedEmbeddingProviders; void EmbedderConfig; void Embedding; void ProviderSpec; void set_rag_config; void BaseClient; void BaseCollectionAddParams; void BaseCollectionParams; void BaseEmbeddingsCallable; void ClientMethodMismatchError; void OpenAIProviderSpec; void AzureProviderSpec; void BedrockProvider; void create_aws_session; void BedrockProviderSpec; void GenerativeAiProviderConfig; void VertexAIProviderConfig; void VertexAIProviderSpec; void MissingChromaDBConfig; void MissingQdrantConfig; void ChromaFactoryModule; void QdrantFactoryModule; void AzureProvider; void AzureProviderConfig; void CohereProvider; void CohereProviderConfig; void CustomEmbeddingFunction; void CustomProvider; void CustomProviderConfig; void GoogleGenAIVertexEmbeddingFunction; void GenerativeAiProvider; void HuggingFaceProvider; void HuggingFaceProviderConfig; void InstructorProvider; void InstructorProviderConfig; void JinaProvider; void JinaProviderConfig; void OllamaProvider; void OllamaProviderConfig; void ONNXProvider; void ONNXProviderConfig; void OpenAIProvider; void OpenAIProviderConfig; void OpenCLIPProvider; void OpenCLIPProviderConfig; void QdrantClient; void RoboflowProvider; void RoboflowProviderConfig; void SentenceTransformerProvider; void SentenceTransformerProviderConfig; void Text2VecProvider; void Text2VecProviderConfig; void VertexAIProvider; void VoyageAIEmbeddingFunction; void VoyageAIProvider; void VoyageAIProviderConfig; void WatsonXEmbeddingFunction; void WatsonXProvider; void WatsonXProviderConfig;",
    "void JsonProvider; void StateBaseProvider; void Auth0Provider; void BaseProvider; void ENV_VARS; void JSON_URL; void MODELS; void PROVIDERS; void check_version; void get_latest_version_from_pypi; void is_current_version_yanked; void is_newer_version_available; void ArtifactNotFoundError; void ContentTypeNegotiationError; void ERROR_MESSAGES; void JSONParseError; void NegotiatedContentTypes; void negotiate_content_types; void validate_content_type; void Action; void STANDARD_CATALOG_COMPONENTS; void A2UIMessage; void BeginRendering; void extract_a2ui_json_objects; void A2UIMessageV09; void BASIC_CATALOG_COMPONENTS; void TextV09; void extract_a2ui_v09_json_objects; void A2UIClientExtension; void A2UIConversationState; void is_v08_message; void is_v09_message; void A2UIServerExtension; void A2UI_EXTENSION_URI; void A2UI_MIME_TYPE; void A2UIValidationError; void validate_a2ui_message; void validate_catalog_components_v09; void APPLICATION_A2UI_JSON; void TEXT_PLAIN; void get_part_content_type; void RedisCacheConfig; void cancel; void cancellable; void execute; void execute_with_extensions; void list_tasks; void A2AClientConfigTypes; void A2AConfigTypes; void create_agent_response_model; void extract_a2a_agent_ids_from_config; void get_a2a_agents_and_response_model; void APIKeyServerAuth; void CoercedSecretStr; void JWTAlgorithm; void MTLSServerAuth; void OAuth2ServerAuth; void JSONFormatter; void LogContext; void configure_json_logging; void get_logger; void SigningAlgorithm; void get_key_id_from_signature; void sign_agent_card; void verify_agent_card_signature; void DelegationContext; void DelegationState; void wrap_agent_with_a2a_instance; void A2AExtension; void ConversationState; void ExtensionRegistry; void ValidatedA2AExtension; void ExtensionsMiddleware; void create_extension_registry_from_config; void get_extensions_from_config; void validate_required_extensions; void ExtensionContext; void ServerExtension; void ServerExtensionRegistry; void configure_auth_client; void parse_www_authenticate; void retry_on_401; void validate_auth_against_agent_card; void aexecute_a2a_delegation; void execute_a2a_delegation; void get_handler; void afetch_agent_card; void fetch_agent_card; void inject_a2a_server_methods; void SendMessageEvent; void TaskStateResult; void MAX_RESUBSCRIBE_ATTEMPTS; void RESUBSCRIBE_BACKOFF_BASE; void StreamingHandler; void LLMCallHookContext; void BeforeLLMCallHook; void Hook; void ReturnT; void AfterLLMCallHookMethod; void BeforeToolCallHookMethod; void BaseEventListener; void CheckpointBaseEvent; void CheckpointForkBaseEvent; void CheckpointRestoreBaseEvent; void CircularDependencyError; void Depends; void FlowEvent; void ReasoningEvent; void ToolUsageEvent; void crewaiEventBus; void crewai_event_bus; void AsyncHandler; void AsyncHandlerSet; void ExecutionPlan; void Handler; void SyncHandler; void SyncHandlerSet; void SIGNAL_EVENT_TYPES; void SignalEvent; void on_signal; void signal_event_adapter; void ENV_CONTEXT_EVENT_TYPES; void EnvContextEvent; void env_context_event_adapter; void MismatchBehavior; void handle_empty_pop; void handle_mismatch; void resume_task_scope; void AgentAggregatedEvaluationResult; void AgentEvaluationResult; void AgentEvaluator; void AggregationStrategy; void BaseEvaluator; void EvaluationScore; void EvaluationTraceCallback; void ExecutionState; void ExperimentResult; void ExperimentResults; void MetricCategory; void ParameterExtractionEvaluator; void ReasoningEfficiencyEvaluator; void ReasoningPatternType; void ToolInvocationEvaluator; void ToolSelectionEvaluator; void assert_experiment_no_regression; void assert_experiment_successfully; void create_default_evaluator; void create_evaluation_callbacks; void run_experiment; void AsyncExecutorContext; void ExecutorContext; void HumanInputProvider; void get_provider; void reset_provider; void set_provider; void ContentProcessorProvider; void NoOpContentProcessor; void get_processor; void process_content; void set_processor; void sanitizeToolName; void UsageMetrics; void SerializableCallable; void StringKnowledgeSource;",
    "void AgentResponseProtocol; void HANDLER_REGISTRY; void HandlerType; void PartsDict; void PartsMetadataDict; void PollingHandlerType; void ProtocolVersion; void PushNotificationHandlerType; void StreamingHandlerType; void Url; void BaseHandlerKwargs; void CommonParams; void PollingHandlerKwargs; void PushNotificationHandlerKwargs; void PushNotificationResultStore; void StreamingHandlerKwargs; void UpdateHandler; void extract_common_params; void PushNotificationConfig; void SignatureInput; void WebhookSignatureConfig; void WebhookSignatureMode; void NegotiationSource; void TransportProtocol; void build_a2ui_system_prompt; void build_a2ui_v09_system_prompt; void CrewAIEventsBus; void EventListener; void HandlerGraph; void build_execution_plan; void is_async_handler; void is_call_handler_safe; void TraceBatch; void TraceBatchManager; void get_user_id; void is_first_execution; void is_tracing_enabled_in_context; void mark_first_execution_completed; void reset_tracing_enabled; void safe_serialize_to_dict; void set_suppress_tracing_messages; void set_tracing_enabled; void should_enable_tracing; void truncate_messages; void BG_CARD; void BG_DARK; void BORDER_SUBTLE; void CREWAI_ORANGE; void CSSExtension; void DARK_GRAY; void GRAY; void JSExtension; void TEXT_PRIMARY; void TEXT_SECONDARY; void WHITE; void calculate_node_positions; void render_interactive; void NodeMetadata; void StructureEdge; void BaseInterceptor; void HookU; void AsyncHTTPTransport; void HTTPTransportKwargs;",
    "void BaseTool; void CrewStructuredTool; void EnvVar; void toolDecorator; void Memory; void CheckpointConfig; void CheckpointEventType; void apply_checkpoint; void FlowMethodData; void FlowExecutionData; void PendingListenerKey; void AND_CONDITION; void OR_CONDITION; void FlowMethod; void StartMethod; void FlowConditionType; void dfs_ancestors; void is_ancestor; void is_flow_condition_dict; void is_flow_condition_list; void is_flow_method; void is_flow_method_callable; void is_flow_method_name; void is_simple_flow_condition; void process_router_paths; void build_task_prompt_with_schema; void prepare_tools; void TaskExecutionData; void setup_agents;",
    "",
  ].join("\n"));

  execFileSync("npm", ["install", "--silent"], { cwd: appDir, stdio: "inherit" });
  const output = execFileSync("node", ["index.mjs"], { cwd: appDir, encoding: "utf8" }).trim();
  if (output !== "true true true true 1.14.6 sequential") {
    throw new Error(`Unexpected package import output: ${output}`);
  }
  execFileSync("npx", ["tsc", "--noEmit"], { cwd: appDir, stdio: "inherit" });
  console.log("pack smoke ok");
} finally {
  rmSync(workspace, { recursive: true, force: true });
}
