import { readFileSync } from "node:fs";

import { __version__ as CREWAI_VERSION } from "./version.js";

export {
  A2AConfig,
  A2AConfigTypes,
  A2AClientConfig,
  A2AClientConfigTypes,
  A2AError,
  A2AErrorCode,
  A2A_ERROR_MESSAGES,
  APPLICATION_A2UI_JSON,
  APPLICATION_JSON,
  APPLICATION_OCTET_STREAM,
  APPLICATION_PDF,
  A2APollingTimeoutError,
  A2AServerConfig,
  A2ATransport,
  A2AHTTPException,
  A2ATaskState,
  ACTIONABLE_STATES,
  AVAILABLE_AGENTS_TEMPLATE,
  AgentResponseProtocol,
  A2AExtension,
  APIKeyServerAuth,
  APIKeyAuth,
  ArtifactNotFoundError,
  AuthScheme,
  AuthenticatedUser,
  AuthenticatedExtendedCardNotConfiguredError,
  AuthenticationRequiredError,
  AuthorizationFailedError,
  BearerTokenAuth,
  ClientTransportConfig,
  ClientAuthScheme,
  CONVERSATION_TURN_INFO_TEMPLATE,
  ContentTypeNegotiationError,
  ContentTypeNotSupportedError,
  ContextNotFoundError,
  BaseHandlerKwargs,
  DelegationContext,
  DelegationState,
  DEFAULT_CLIENT_INPUT_MODES,
  DEFAULT_CLIENT_OUTPUT_MODES,
  DEFAULT_TRANSPORT_PREFERENCE,
  ERROR_MESSAGES,
  EnterpriseTokenAuth,
  ExtensionContext,
  ExtensionRegistry,
  ExtensionsMiddleware,
  GRPCClientConfig,
  GRPCServerConfig,
  GRPC_TRANSPORT,
  HTTPBasicAuth,
  HTTPDigestAuth,
  HTTPJSONConfig,
  HTTP_JSON_TRANSPORT,
  IMAGE_JPEG,
  IMAGE_PNG,
  IMAGE_WILDCARD,
  InternalError,
  InvalidAgentResponseError,
  InvalidParamsError,
  InvalidRequestError,
  JSONParseError,
  JSONFormatter,
  JSONRPCClientConfig,
  JSONRPCServerConfig,
  JSONRPC_TRANSPORT,
  JWTAlgorithm,
  LogContext,
  MethodNotFoundError,
  MTLSServerAuth,
  NegotiatedContentTypes,
  NegotiatedTransport,
  OAuth2AuthorizationCode,
  OAuth2ClientCredentials,
  OAuth2ServerAuth,
  OIDCAuth,
  PartsDict,
  PartsMetadataDict,
  PREVIOUS_A2A_CONVERSATION_TEMPLATE,
  PENDING_STATES,
  MAX_RESUBSCRIBE_ATTEMPTS,
  PollingConfig,
  PollingHandler,
  PollingHandlerKwargs,
  PollingHandlerType,
  ProtocolVersion,
  PushNotificationConfig,
  PushNotificationNotSupportedError,
  PushNotificationHandler,
  PushNotificationHandlerKwargs,
  PushNotificationHandlerType,
  PushNotificationResultStore,
  RateLimitExceededError,
  RedisCacheConfig,
  REMOTE_AGENT_COMPLETED_NOTICE,
  REMOTE_AGENT_RESPONSE_NOTICE,
  RESUBSCRIBE_BACKOFF_BASE,
  ServerAuthScheme,
  ServerExtension,
  ServerExtensionRegistry,
  ServerPushNotificationConfig,
  ServerTransportConfig,
  SigningAlgorithm,
  SimpleTokenAuth,
  SkillNotFoundError,
  StreamingConfig,
  TEXT_PLAIN,
  TaskNotFoundError,
  TaskNotCancelableError,
  TaskTimeoutError,
  TLSConfig,
  TERMINAL_STATES,
  TransportProtocol,
  TransportNegotiationError,
  TransportNegotiationFailedError,
  NegotiationSource,
  StreamingHandlerKwargs,
  StreamingHandler,
  StreamingHandlerType,
  UNAVAILABLE_AGENTS_NOTICE_TEMPLATE,
  UpdateConfig,
  UpdateHandler,
  UnsupportedExtensionError,
  UnsupportedOperationError,
  UnsupportedVersionError,
  Url,
  ValidatedA2AExtension,
  WebhookSignatureConfig,
  WebhookSignatureMode,
  aexecute_a2a_delegation,
  afetch_agent_card,
  build_a2ui_system_prompt,
  build_a2ui_v09_system_prompt,
  createErrorResponse,
  create_error_response,
  create_agent_response_model,
  create_extension_registry_from_config,
  configure_auth_client,
  configure_json_logging,
  cancel,
  cancellable,
  execute,
  execute_a2a_delegation,
  execute_with_extensions,
  extractCommonParams,
  extract_common_params,
  extract_a2a_agent_ids_from_config,
  extractErrorMessage,
  extractTaskResultParts,
  extract_error_message,
  extract_task_result_parts,
  getPartContentType,
  getServerInterfaces,
  get_a2a_agents_and_response_model,
  get_extensions_from_config,
  get_key_id_from_signature,
  get_logger,
  get_handler,
  get_part_content_type,
  get_server_interfaces,
  isClientError,
  isRetryableError,
  is_client_error,
  is_retryable_error,
  fetch_agent_card,
  inject_a2a_server_methods,
  list_tasks,
  negotiateContentTypes,
  negotiateTransport,
  negotiate_content_types,
  negotiate_transport,
  processTaskState,
  process_task_state,
  renderA2ATemplate,
  render_a2a_template,
  sendMessageAndGetTaskId,
  send_message_and_get_task_id,
  task_to_skill,
  parse_www_authenticate,
  retry_on_401,
  SendMessageEvent,
  SignatureInput,
  sign_agent_card,
  CommonParams,
  CoercedSecretStr,
  ConversationState,
  HANDLER_REGISTRY,
  HandlerType,
  TaskStateResult,
  validateContentType,
  validateMessageParts,
  validate_content_type,
  validate_message_parts,
  validate_auth_against_agent_card,
  validate_required_extensions,
  verify_agent_card_signature,
  wrap_agent_with_a2a_instance,
  agent_to_agent_card,
  tool_to_skill,
  _agent_to_agent_card,
  _task_to_skill,
  _tool_to_skill,
  type A2AAgentSkill,
  type A2AAgentCard,
  type A2AAgentInterface,
  type A2AAgentResponseProtocol,
  type A2AArtifactLike,
  type A2AClientConfigOptions,
  type A2AClientConfigTypes as A2AClientConfigTypesOptions,
  type A2AConfigTypes as A2AConfigTypesOptions,
  type A2AMessageLike,
  type A2ANegotiationSource,
  type A2APartsDict,
  type A2APartsMetadataDict,
  type A2AProtocolVersion,
  type A2AServerConfigOptions,
  type A2ATaskLike,
  type A2ATextPartLike,
  type A2AStreamingClient,
  type A2ATaskStateResult,
  type A2ATransportProtocol,
  type A2AHeaders,
  type A2AExecutionContext,
  type A2AEventQueue,
  type A2AExtensionRegistry,
  type APIKeyLocation,
} from "./a2a.js";
export {
  A2UIEvent,
  A2UIEventV09,
  A2UIAnyMessageDict,
  A2UIClientExtension,
  A2UIConversationState,
  A2UI_EXTENSION_URI,
  A2UIMessage,
  A2UIMessageDict,
  A2UIMessageV09,
  A2UIMessageV09Dict,
  A2UIValidationError,
  A2UI_MIME_TYPE,
  A2UIModel,
  A2UIResponse,
  A2UI_STANDARD_CATALOG_ID,
  A2UI_V09_BASIC_CATALOG_ID,
  A2UI_V09_EXTENSION_URI,
  A2UIServerExtension,
  AccessibilityAttributes,
  Action,
  ActionBoundValue,
  ActionContextEntry,
  ActionEvent,
  ActionV09,
  ArrayBinding,
  AudioPlayer,
  AudioPlayerV09,
  BeginRendering,
  BeginRenderingDict,
  BASIC_CATALOG_COMPONENTS,
  BASIC_CATALOG_FUNCTIONS,
  BooleanBinding,
  BoundValue,
  Button,
  ButtonV09,
  Card,
  CardV09,
  CheckBox,
  CheckBoxV09,
  CheckRule,
  ChildListV09,
  ChildTemplate,
  ChildrenDef,
  ChoicePickerOption,
  ChoicePickerV09,
  ClientDataModel,
  ClientError,
  ClientErrorV09,
  ComponentEntryDict,
  Column,
  ColumnV09,
  ComponentEntry,
  ComponentName,
  CreateSurface,
  CreateSurfaceDict,
  DataBinding,
  DataEntry,
  DataEntryDict,
  DataModelUpdate,
  DataModelUpdateDict,
  DateTimeInput,
  DateTimeInputV09,
  DeleteSurface,
  DeleteSurfaceDict,
  DeleteSurfaceV09,
  DeleteSurfaceV09Dict,
  Divider,
  DividerV09,
  DynamicBoolean,
  DynamicNumber,
  DynamicString,
  DynamicStringList,
  DynamicValue,
  EventAction,
  FunctionCall,
  FunctionName,
  Icon,
  IconBinding,
  IconName,
  IconNameV09,
  IconV09,
  Image,
  ImageV09,
  List,
  ListV09,
  MapEntry,
  Modal,
  ModalV09,
  MultipleChoice,
  MultipleChoiceOption,
  NumberBinding,
  Row,
  RowV09,
  SCHEMA_NAMES,
  STANDARD_CATALOG_COMPONENTS,
  Slider,
  SliderV09,
  StringBinding,
  Styles,
  StylesDict,
  SurfaceUpdate,
  SurfaceUpdateDict,
  TabItem,
  TabItemV09,
  Tabs,
  TabsV09,
  Text,
  TextField,
  TextFieldV09,
  TextV09,
  Theme,
  ThemeDict,
  UpdateComponents,
  UpdateComponentsDict,
  UpdateDataModel,
  UpdateDataModelDict,
  UserAction,
  V09_ICON_NAMES,
  V09_SCHEMA_NAMES,
  Video,
  VideoV09,
  extractA2UIJsonObjects,
  extractA2UIV09JsonObjects,
  extract_a2ui_json_objects,
  extract_a2ui_v09_json_objects,
  isV08Message,
  isV09Message,
  is_v08_message,
  is_v09_message,
  loadSchema,
  load_schema,
  validateA2UIEvent,
  validateA2UIEventV09,
  validateA2UIMessage,
  validateA2UIMessageV09,
  validateCatalogComponents,
  validateCatalogComponentsV09,
  validate_a2ui_event,
  validate_a2ui_event_v09,
  validate_a2ui_message,
  validate_a2ui_message_v09,
  validate_catalog_components,
  validate_catalog_components_v09,
  type A2UIRecord,
} from "./a2ui.js";
export { Agent, type AgentExecutionOptions, type AgentKickoffInput, type AgentOptions, type CodeExecutionMode } from "./agent.js";
export {
  BaseAgentAdapter,
  BaseConverterAdapter,
  BaseToolAdapter,
  FunctionTool,
  LangGraphAgentAdapter,
  LangGraphCheckPointMemoryModule,
  LangGraphConverterAdapter,
  LangGraphMemorySaver,
  LangGraphPrebuiltModule,
  LangGraphToolAdapter,
  OpenAIAgent,
  OpenAIAgentAdapter,
  OpenAIAgentToolAdapter,
  OpenAIAgentsModule,
  OpenAIConverterAdapter,
  OpenAIFunctionTool,
  OpenAIRunner,
  OpenAITool,
  Runner,
  Tool as OpenAIToolProtocol,
  AgentKwargs,
} from "./agent-adapters.js";
export {
  CodeInterpreterFileResult,
  CodeInterpreterLogResult,
  CodeInterpreterResult,
  ComputerUseResult,
  FileSearchResult,
  FileSearchResultItem,
  OPENAI_COMPATIBLE_PROVIDERS,
  OpenAICompletion,
  OpenAICompatibleCompletion,
  ProviderConfig,
  ReasoningSummary,
  ResponsesAPIResult,
  WebSearchResult,
  type OpenAICompletionOptions,
  type ProviderConfigOptions,
  type ResponsesAPIResultOptions,
} from "./openai-completion.js";
export {
  ANTHROPIC_FILES_API_BETA,
  ANTHROPIC_STRUCTURED_OUTPUTS_BETA,
  AnthropicCompletion,
  AnthropicThinkingConfig,
  AnthropicToolSearchConfig,
  AzureCompletion,
  AzureCompletionParams,
  BedrockCompletion,
  BedrockConverseRequestBody,
  BedrockConverseStreamRequestBody,
  ConverseToolTypeDef,
  GeminiCompletion,
  NATIVE_STRUCTURED_OUTPUT_MODELS,
  STRUCTURED_OUTPUT_TOOL_NAME,
  TOOL_SEARCH_TOOL_TYPES,
  ToolInputSchema,
  ToolSpec,
  type AnthropicCompletionOptions,
  type AnthropicThinkingConfigOptions,
  type AnthropicToolSearchConfigOptions,
  type AzureCompletionOptions,
  type BedrockCompletionOptions,
  type GeminiCompletionOptions,
} from "./provider-completions.js";
export {
  AgentPlanning,
  AgentPlanningOutput,
  AgentReasoning,
  AgentReasoningOutput,
  FUNCTION_SCHEMA,
  PlanStep,
  PlanningConfig,
  PlanningPlan,
  REASONING_READY_MARKER,
  ReasoningPlan,
  StepObservation,
  StepRefinement,
  TodoItem,
  TodoList,
  TodoStatus,
  createAgentRefinePlanningPrompt,
  createAgentPlanningPrompt,
  createAgentPlanningSystemPrompt,
  createDefaultPlanningConfigForFlag,
  normalizePlanningConfig,
  parseAgentPlanningOutput,
  type AgentPlanStep,
  type AgentReasoningPlan,
  type PlanningConfigOptions,
  type ReasoningEffort,
} from "./agent-planning.js";
export {
  DELEGATION_TOOL_NAMES,
  NativeToolCallResult,
  SummaryContent,
  aget_llm_response,
  buildToolCallsAssistantMessage,
  build_tool_calls_assistant_message,
  checkNativeToolSupport,
  check_native_tool_support,
  convertToolsToOpenAISchema,
  convert_tools_to_openai_schema,
  enforceRpmLimit,
  enforce_rpm_limit,
  executeSingleNativeToolCall,
  execute_single_native_tool_call,
  extractToolCallInfo,
  extractTaskSection,
  extract_task_section,
  extract_tool_call_info,
  formatMessageForLLM,
  format_message_for_llm,
  formatAnswer,
  format_answer,
  getLlmResponse,
  getToolNames,
  get_llm_response,
  get_tool_names,
  handleAgentActionCore,
  handleContextLength,
  handleMaxIterationsExceeded,
  handleOutputParserException,
  handleUnknownError,
  handle_agent_action_core,
  handle_context_length,
  handle_max_iterations_exceeded,
  handle_output_parser_exception,
  handle_unknown_error,
  hasReachedMaxIterations,
  has_reached_max_iterations,
  isContextLengthExceeded,
  isInsideEventLoop,
  isToolCallList,
  is_context_length_exceeded,
  is_inside_event_loop,
  is_tool_call_list,
  loadAgentFromRepository,
  load_agent_from_repository,
  parseToolCallArgs,
  parseTools,
  parse_tool_call_args,
  parse_tools,
  processLlmResponse,
  process_llm_response,
  renderTextDescriptionAndArgs,
  render_text_description_and_args,
  setupNativeTools,
  setup_native_tools,
  showAgentLogs,
  show_agent_logs,
  summarizeMessages,
  summarize_messages,
  trackDelegationIfNeeded,
  track_delegation_if_needed,
  type NativeToolCallResultOptions,
  type OpenAIFunctionToolSchema,
  type OpenAIToolConversionResult,
  type ToolRunner,
} from "./agent-utils.js";
export {
  ACTION_INPUT_ONLY_REGEX,
  ACTION_INPUT_REGEX,
  ACTION_REGEX,
  AgentExecutor,
  AgentExecutorState,
  BaseAgent,
  BaseAgentExecutor,
  CrewAgentExecutor,
  CrewAgentExecutorFlow,
  OutputConverter,
  PlannerObserver,
  PlatformApp,
  PlatformAppOrAction,
  StepExecutor,
  TokenProcess,
  parseAgentStep,
  parse_agent_step,
  type BaseAgentExecutorOptions,
  type StepExecutorOptions,
} from "./agent-executors.js";
export {
  AgentAction,
  AgentFinish,
  FINAL_ANSWER_ACTION,
  FINAL_ANSWER_AND_PARSABLE_ACTION_ERROR_MESSAGE,
  MISSING_ACTION_AFTER_THOUGHT_ERROR_MESSAGE,
  MISSING_ACTION_INPUT_AFTER_ACTION_ERROR_MESSAGE,
  OutputParserError,
  UNABLE_TO_REPAIR_JSON_RESULTS,
  parse,
  parseAgentOutput,
  parse_agent_output,
} from "./agent-parser.js";
export {
  ALGORITHMS,
  Auth0Provider,
  AuthError,
  AuthenticationCommand,
  BaseProvider,
  BaseProvider as BaseAuthProvider,
  EntraIdProvider,
  KeycloakProvider,
  Oauth2Settings,
  OktaProvider,
  ProviderFactory,
  TokenManager,
  WorkosProvider,
  constantTimeEquals,
  createTemporaryTokenStorage,
  getAuthToken,
  get_auth_token,
  validateJwtToken,
  validate_jwt_token,
  type AuthenticationCommandOptions,
  type DeviceCodeData,
  type Oauth2SettingsOptions,
  type ProviderConstructor,
  type TokenManagerOptions,
  type TokenResponseData,
  type ValidateJwtTokenOptions,
} from "./auth.js";
export { Crew, type CrewOptions, type KickoffForEachOptions, type KickoffOptions, type ReplayTaskRef, type ResetMemoriesCommandType, type TaskExecutionLog } from "./crew.js";
export {
  ChatInputField,
  ChatInputs,
  DEFAULT_CREW_DESCRIPTION,
  DEFAULT_INPUT_DESCRIPTION,
  MIN_REQUIRED_CONVERSATIONAL_CREW_VERSION,
  MIN_REQUIRED_VERSION,
  buildSystemMessage,
  build_system_message,
  checkConversationalCrewsVersion,
  check_conversational_crews_version,
  chatLoop,
  chat_loop,
  createToolFunction,
  create_tool_function,
  fetchRequiredInputs,
  fetch_required_inputs,
  flushInput,
  flush_input,
  generateCrewChatInputs,
  generateCrewDescriptionWithAi,
  generateCrewToolSchema,
  generateInputDescriptionWithAi,
  generate_crew_chat_inputs,
  generate_crew_description_with_ai,
  generate_crew_tool_schema,
  generate_input_description_with_ai,
  getUserInput,
  get_user_input,
  handleUserInput,
  handle_user_input,
  initializeChatLlm,
  initialize_chat_llm,
  loadCrewAndName,
  load_crew_and_name,
  runChat,
  run_chat,
  runCrewTool,
  run_crew_tool,
  setCrewChatLoader,
  set_crew_chat_loader,
  showLoading,
  show_loading,
  type ChatInputFieldOptions,
  type ChatInputsOptions,
  type ChatLoopOptions,
  type CrewChatLoader,
  type CrewChatToolSchema,
  type GenerateCrewChatInputsOptions,
} from "./crew-chat.js";
export {
  EmptyStackError,
  EventContextConfig,
  EventPairingError,
  ExecutionContext,
  FlowTrackable,
  SCOPE_ENDING_EVENTS,
  SCOPE_STARTING_EVENTS,
  StackDepthExceededError,
  VALID_EVENT_PAIRS,
  applyExecutionContext,
  apply_execution_context,
  captureExecutionContext,
  capture_execution_context,
  eventScope,
  event_scope,
  currentFlowId,
  currentFlowMethodName,
  currentFlowRequestId,
  current_flow_id,
  current_flow_method_name,
  current_flow_request_id,
  getCurrentParentId,
  getCurrentTaskId,
  getCurrentFlowId,
  getCurrentFlowMethodName,
  getCurrentFlowRequestId,
  getEmissionSequence,
  getEnclosingParentId,
  getEventContextConfig,
  getLastEventId,
  getPlatformIntegrationToken,
  getTriggeringEventId,
  get_current_parent_id,
  get_current_task_id,
  get_current_flow_id,
  get_current_flow_method_name,
  get_current_flow_request_id,
  get_emission_sequence,
  get_enclosing_parent_id,
  get_event_context_config,
  get_last_event_id,
  get_platform_integration_token,
  get_triggering_event_id,
  handleEmptyPop,
  handleMismatch,
  handle_empty_pop,
  handle_mismatch,
  MismatchBehavior,
  platformContext,
  platform_context,
  popEventScope,
  pop_event_scope,
  pushEventScope,
  push_event_scope,
  resetCurrentTaskId,
  resetEmissionCounter,
  resetLastEventId,
  reset_current_task_id,
  reset_emission_counter,
  reset_last_event_id,
  restoreEventScope,
  restore_event_scope,
  resume_task_scope,
  runWithExecutionContext,
  run_with_execution_context,
  setCurrentFlowContext,
  setCurrentTaskId,
  setEmissionCounter,
  setEventContextConfig,
  setLastEventId,
  setPlatformIntegrationToken,
  setTriggeringEventId,
  set_current_flow_context,
  set_current_task_id,
  set_emission_counter,
  set_event_context_config,
  set_last_event_id,
  set_platform_integration_token,
  set_triggering_event_id,
  triggeredByScope,
  triggered_by_scope,
  type EventContextConfigOptions,
  type EventScopeEntry,
  type ExecutionContextOptions,
} from "./context.js";
export {
  ContentProcessorProvider,
  NoOpContentProcessor,
  get_processor,
  process_content,
  set_processor,
  type ContentProcessorProvider as ContentProcessorProviderType,
} from "./content-processor.js";
export { processConfig, process_config } from "./config-utils.js";
export {
  CreateConverterKwargs,
  Converter,
  ConverterError,
  asyncConvertToModel,
  asyncConvertWithInstructions,
  asyncHandlePartialJson,
  async_convert_to_model,
  async_convert_with_instructions,
  async_handle_partial_json,
  convertToModel,
  convertWithInstructions,
  convertWithInstructionsSync,
  convert_to_model,
  convert_with_instructions,
  convert_with_instructions_sync,
  createConverter,
  create_converter,
  getConversionInstructions,
  get_conversion_instructions,
  handlePartialJson,
  handle_partial_json,
  validateModel,
  validate_model,
  type ConversionAgent,
  type ConverterOptions,
  type StructuredModel,
} from "./converter.js";
export {
  CrewEvaluator,
  Entity,
  AgentAggregatedEvaluationResult,
  AgentEvaluationResult,
  AgentEvaluator,
  AggregationStrategy,
  BaseEvaluator,
  EvaluationScore,
  EvaluationTraceCallback,
  EvaluationDisplayFormatter,
  ExecutionState,
  ExperimentResult,
  ExperimentResults,
  ExperimentResultsDisplay,
  ExperimentRunner,
  GoalAlignmentEvaluator,
  MetricCategory,
  ParameterExtractionEvaluator,
  ReasoningEfficiencyEvaluator,
  ReasoningPatternType,
  SemanticQualityEvaluator,
  TaskEvaluation,
  TaskEvaluationModel,
  TaskEvaluationPydanticOutput,
  TaskEvaluationPydanticOutputModel,
  TaskEvaluator,
  ToolInvocationEvaluator,
  ToolSelectionEvaluator,
  TrainingTaskEvaluation,
  TrainingTaskEvaluationModel,
  assert_experiment_no_regression,
  assert_experiment_successfully,
  create_default_evaluator,
  create_evaluation_callbacks,
  run_experiment,
  taskEvaluationModel,
  taskEvaluationPydanticOutputModel,
  trainingTaskEvaluationModel,
  type CrewLikeForEvaluation,
  type EvaluationAgentLike,
} from "./evaluators.js";
export {
  ForEachStreamingContext,
  StreamingContext,
  TaskExecutionData,
  ahandle_knowledge_retrieval,
  applyTrainingData,
  apply_training_data,
  buildTaskPromptWithSchema,
  build_task_prompt_with_schema,
  checkConditionalSkip,
  check_conditional_skip,
  enableAgentStreaming,
  enable_agent_streaming,
  formatTaskWithContext,
  format_task_with_context,
  getKnowledgeConfig,
  get_knowledge_config,
  handleKnowledgeRetrieval,
  handleReasoning,
  handle_knowledge_retrieval,
  handle_reasoning,
  prepareKickoff,
  prepareTaskExecution,
  prepareTools,
  prepare_kickoff,
  prepare_task_execution,
  prepare_tools,
  processToolResults,
  process_tool_results,
  runForEachAsync,
  run_for_each_async,
  saveLastMessages,
  save_last_messages,
  setupAgents,
  setup_agents,
  validateMaxExecutionTime,
  validate_max_execution_time,
} from "./execution-utils.js";
export {
  CrewBase,
  afterKickoff,
  after_kickoff,
  agent,
  beforeKickoff,
  before_kickoff,
  cacheHandler,
  cache_handler,
  callback,
  crew,
  llm,
  outputJson,
  output_json,
  outputPydantic,
  output_pydantic,
  task,
  tool,
} from "./decorators.js";
export {
  AfterKickoffMethod,
  AgentConfig,
  AgentMethod,
  BeforeKickoffMethod,
  BoundTaskMethod,
  CacheHandlerMethod,
  CallableT,
  CallbackMethod,
  CrewBaseMeta,
  CrewClass,
  CrewInstance,
  CrewMetadata,
  CrewMethod,
  DecoratedMethod,
  LLMMethod,
  OutputClass,
  OutputJsonClass,
  OutputJsonMethod,
  OutputPydanticClass,
  OutputPydanticMethod,
  P,
  P2,
  R,
  R2,
  SelfT,
  T,
  TaskConfig,
  TaskMethod,
  TaskResult,
  TaskResultT,
  ToolMethod,
  cache,
  closeMcpServer,
  close_mcp_server,
  crewMetadataFor,
  getAllMethods,
  getMcpTools,
  get_all_methods,
  get_mcp_tools,
  loadConfigurations,
  loadProjectConfig,
  loadYaml,
  load_configurations,
  load_yaml,
  mapAllAgentVariables,
  mapAllTaskVariables,
  map_all_agent_variables,
  map_all_task_variables,
  memoize,
} from "./project-compat.js";
export {
  CC_ENV_VAR,
  CODEX_ENV_VARS,
  CURSOR_ENV_VARS,
  getEnvContext,
  get_env_context,
  isCodexEnv,
  isCursorEnv,
  is_codex_env,
  is_cursor_env,
  resetEnvContextForTesting,
  reset_env_context_for_testing,
} from "./env.js";
export {
  AgentRepositoryError,
  CONTEXT_LIMIT_ERRORS,
  DatabaseError,
  DatabaseOperationError,
  LLMContextLengthExceededError,
} from "./errors.js";
export {
  A2AAgentCardFetchedEvent,
  A2AArtifactReceivedEvent,
  A2AAuthenticationFailedEvent,
  A2AConnectionErrorEvent,
  A2AContentTypeNegotiatedEvent,
  A2AContextCompletedEvent,
  A2AContextCreatedEvent,
  A2AContextExpiredEvent,
  A2AContextIdleEvent,
  A2AContextPrunedEvent,
  A2AConversationCompletedEvent,
  A2AConversationStartedEvent,
  A2ADelegationCompletedEvent,
  A2ADelegationStartedEvent,
  A2AEventBase,
  A2AMessageSentEvent,
  A2AParallelDelegationCompletedEvent,
  A2AParallelDelegationStartedEvent,
  A2APollingStartedEvent,
  A2APollingStatusEvent,
  A2APushNotificationReceivedEvent,
  A2APushNotificationRegisteredEvent,
  A2APushNotificationSentEvent,
  A2APushNotificationTimeoutEvent,
  A2AResponseReceivedEvent,
  A2AServerTaskCanceledEvent,
  A2AServerTaskCompletedEvent,
  A2AServerTaskFailedEvent,
  A2AServerTaskStartedEvent,
  A2AStreamingChunkEvent,
  A2AStreamingStartedEvent,
  A2ATransportNegotiatedEvent,
  CCEnvEvent,
  AgentEvaluationCompletedEvent,
  AgentEvaluationFailedEvent,
  AgentEvaluationStartedEvent,
  AgentExecutionCompletedEvent,
  AgentExecutionErrorEvent,
  AgentExecutionStartedEvent,
  AgentLogsExecutionEvent,
  AgentLogsStartedEvent,
  AgentReasoningCompletedEvent,
  AgentReasoningFailedEvent,
  AgentReasoningStartedEvent,
  BaseEvent,
  BaseEventListener,
  ConsoleFormatter,
  CodexEnvEvent,
  CrewAIEventsBus,
  CircularDependencyError,
  CheckpointBaseEvent,
  CrewKickoffCompletedEvent,
  CrewKickoffFailedEvent,
  CrewKickoffStartedEvent,
  CrewBaseEvent,
  CrewTestCompletedEvent,
  CrewTestFailedEvent,
  CrewTestStartedEvent,
  CrewTrainCompletedEvent,
  CrewTrainFailedEvent,
  CrewTrainStartedEvent,
  CursorEnvEvent,
  DefaultEnvEvent,
  Depends,
  EventBus,
  EventHandler,
  EventTypes,
  EventListener,
  FlowCreatedEvent,
  FlowEvent,
  FlowFailedEvent,
  FlowFinishedEvent,
  FlowInputReceivedEvent,
  FlowInputRequestedEvent,
  FlowPausedEvent,
  FlowPlotEvent,
  FlowStartedEvent,
  GoalAchievedEarlyEvent,
  HumanFeedbackReceivedEvent,
  HumanFeedbackRequestedEvent,
  KnowledgeEventBase,
  KnowledgeQueryCompletedEvent,
  KnowledgeQueryFailedEvent,
  KnowledgeQueryStartedEvent,
  KnowledgeRetrievalCompletedEvent,
  KnowledgeRetrievalStartedEvent,
  KnowledgeSearchQueryFailedEvent,
  LLMCallCompletedEvent,
  LLMCallFailedEvent,
  LLMCallStartedEvent,
  LLMCallType,
  LLMEventBase,
  LLMGuardrailBaseEvent,
  LLMGuardrailCompletedEvent,
  LLMGuardrailStartedEvent,
  LLMStreamChunkEvent,
  LLMThinkingChunkEvent,
  ToolCall,
  LiteAgentExecutionCompletedEvent,
  LiteAgentExecutionErrorEvent,
  LiteAgentExecutionStartedEvent,
  MemoryQueryCompletedEvent,
  MemoryQueryFailedEvent,
  MemoryQueryStartedEvent,
  MemoryRetrievalCompletedEvent,
  MemoryRetrievalFailedEvent,
  MemoryRetrievalStartedEvent,
  MemorySaveCompletedEvent,
  MemorySaveFailedEvent,
  MemorySaveStartedEvent,
  MemoryBaseEvent,
  MCPConfigFetchFailedEvent,
  MCPConnectionCompletedEvent,
  MCPConnectionFailedEvent,
  MCPConnectionStartedEvent,
  MCPEvent,
  MCPToolExecutionCompletedEvent,
  MCPToolExecutionFailedEvent,
  MCPToolExecutionStartedEvent,
  MethodExecutionFailedEvent,
  MethodExecutionFinishedEvent,
  MethodExecutionPausedEvent,
  MethodExecutionStartedEvent,
  CheckpointCompletedEvent,
  CheckpointFailedEvent,
  CheckpointForkBaseEvent,
  CheckpointForkCompletedEvent,
  CheckpointForkStartedEvent,
  CheckpointPrunedEvent,
  CheckpointRestoreBaseEvent,
  CheckpointRestoreCompletedEvent,
  CheckpointRestoreFailedEvent,
  CheckpointRestoreStartedEvent,
  CheckpointStartedEvent,
  ObservationEvent,
  PlanRefinementEvent,
  PlanReplanTriggeredEvent,
  ReasoningEvent,
  SkillActivatedEvent,
  SkillDiscoveryCompletedEvent,
  SkillDiscoveryStartedEvent,
  SkillDownloadCompletedEvent,
  SkillDownloadStartedEvent,
  SkillEvent,
  SkillLoadFailedEvent,
  SkillLoadedEvent,
  SigContEvent,
  SigHupEvent,
  SigIntEvent,
  SigTStpEvent,
  SigTermEvent,
  SignalType,
  StepObservationCompletedEvent,
  StepObservationFailedEvent,
  StepObservationStartedEvent,
  CrewTestResultEvent,
  TaskCompletedEvent,
  TaskEvaluationEvent,
  TaskFailedEvent,
  TaskStartedEvent,
  ToolExecutionErrorEvent,
  ToolSelectionErrorEvent,
  ToolUsageErrorEvent,
  ToolUsageEvent,
  ToolUsageFinishedEvent,
  ToolUsageStartedEvent,
  ToolValidateInputErrorEvent,
  crewaiEventBus,
  crewai_event_bus,
  build_execution_plan,
  is_async_handler,
  is_call_handler_safe,
  resetEmissionSequence,
  AsyncHandler,
  AsyncHandlerSet,
  ExecutionPlan,
  EventT_co,
  ENV_CONTEXT_EVENT_TYPES,
  EnvContextEvent,
  env_context_event_adapter,
  Handler,
  HandlerGraph,
  on_signal,
  SIGNAL_EVENT_TYPES,
  SignalEvent,
  signal_event_adapter,
  SyncHandler,
  SyncHandlerSet,
  TraceBatch,
  TraceBatchManager,
  TraceCollectionListener,
  TraceEvent,
  FirstTimeTraceHandler,
  event_listener,
  get_next_emission_sequence,
  is_replaying,
  type A2AAgentCardMetadata,
  type A2ACommonEventOptions,
  type A2AEventMetadata,
  type BaseEventOptions,
  type CrewAIEvent,
  type EventType,
  type KnowledgeCommonEventOptions,
  type LLMCallType as LLMCallTypeValue,
  type LLMCommonEventOptions,
  type LLMEventMessage,
  type LLMFunctionCall,
  type LLMGuardrailCommonEventOptions,
  type LLMToolCall,
  type MCPCommonEventOptions,
  type ObservationCommonEventOptions,
  type SkillCommonEventOptions,
} from "./events.js";
export {
  DEFAULT_FILE_STORE_TTL,
  aclearFiles,
  aclearTaskFiles,
  aclear_files,
  aclear_task_files,
  agetAllFiles,
  agetFiles,
  agetTaskFiles,
  aget_all_files,
  aget_files,
  aget_task_files,
  astoreFiles,
  astoreTaskFiles,
  astore_files,
  astore_task_files,
  clearFileStore,
  clearFiles,
  clearTaskFiles,
  clear_file_store,
  clear_files,
  clear_task_files,
  getAllFiles,
  getFiles,
  getTaskFiles,
  get_all_files,
  get_files,
  get_task_files,
  storeFiles,
  storeTaskFiles,
  store_files,
  store_task_files,
  type FileInput,
  type FileInputMap,
} from "./file-store.js";
export { FileHandler, LogEntry, PickleHandler } from "./file-handler.js";
export {
  DIVIDERS,
  aggregateRawOutputsFromTaskOutputs,
  aggregateRawOutputsFromTasks,
  aggregate_raw_outputs_from_task_outputs,
  aggregate_raw_outputs_from_tasks,
} from "./formatter.js";
export {
  AND_CONDITION,
  Flow,
  CompletedMethodData,
  ConsoleProvider,
  DistilledLessons,
  EdgeInfo,
  ExecutionMethodData,
  F,
  F as FlowTypeF,
  FlowCondition,
  FlowConditionType,
  FlowConditions,
  FlowData,
  FlowExecutionData,
  FlowMeta,
  FlowMethod,
  FlowMethodCallable,
  FlowMethodData,
  FlowMethodName,
  FlowRouteName,
  FlowState,
  FlowStructure,
  FlowStructureInfo,
  InputHistoryEntry,
  InputProvider,
  InputResponse,
  ListenMethod,
  OR_CONDITION,
  P as FlowTypeP,
  PendingListenerKey,
  PendingFeedbackContext,
  PreReviewResult,
  R as FlowTypeR,
  RouterMethod,
  SimpleFlowCondition,
  StartMethod,
  T as FlowTypeT,
  LockedDictProxy,
  LockedListProxy,
  MethodInfo,
  StateFieldInfo,
  StateProxy,
  StateSchemaInfo,
  and_,
  buildAncestorDict,
  buildParentChildrenDict,
  build_ancestor_dict,
  build_parent_children_dict,
  buildFlowStructure,
  build_flow_structure,
  calculateExecutionPaths,
  calculateNodeLevels,
  calculate_execution_paths,
  calculate_node_levels,
  countOutgoingEdges,
  count_outgoing_edges,
  dfsAncestors,
  dfs_ancestors,
  extractMethodSignature,
  extract_method_signature,
  flow_config,
  flowStructure,
  flow_structure,
  getChildIndex,
  get_child_index,
  getFlowMetadata,
  getFlowStructure,
  get_flow_structure,
  getPossibleReturnConstants,
  get_possible_return_constants,
  getHumanFeedbackMetadata,
  HumanFeedbackConfig,
  HumanFeedbackMethod,
  HumanFeedbackProvider,
  HumanFeedbackResult,
  humanFeedback,
  human_feedback,
  HumanFeedbackPending,
  isAncestor,
  isFlowConditionDict,
  isFlowConditionList,
  isFlowMethod,
  isFlowMethodCallable,
  isFlowMethodName,
  isSimpleFlowCondition,
  is_ancestor,
  is_flow_condition_dict,
  is_flow_condition_list,
  is_flow_method,
  is_flow_method_callable,
  is_flow_method_name,
  is_simple_flow_condition,
  listen,
  or_,
  processRouterPaths,
  process_router_paths,
  router,
  start,
  visualizeFlowStructure,
  visualize_flow_structure,
  type FlowAskOptions,
  type FlowCondition as FlowConditionOptions,
  type FlowConditionInput,
  type FlowCompletedMethodData,
  type FlowExecutionData as FlowExecutionDataOptions,
  type FlowExecutionMethodData,
  type FlowExecutionTraceEntry,
  type FlowKickoffOptions,
  type FlowInputHistoryEntry,
  type FlowMethodEntry,
  type FlowMethodKind,
  type FlowMethodSignature,
  type FlowNodeMetadata,
  type FlowOptions,
  type FlowSerializedEdgeInfo,
  type FlowSerializedMethodInfo,
  type FlowSerializedStateFieldInfo,
  type FlowSerializedStateSchemaInfo,
  type FlowSerializedStructureInfo,
  type FlowStructureEdge,
  type FlowStructureMethod,
  type FlowVisualizationEdge,
  type FlowVisualizationStructure,
  type HumanFeedbackContext,
  type OpenAPISchema,
  typeToOpenAPISchema,
  type_to_openapi_schema,
} from "./flow.js";
export {
  BG_CARD,
  BG_DARK,
  BORDER_SUBTLE,
  CREWAI_ORANGE,
  CSSExtension,
  DARK_GRAY,
  GRAY,
  JSExtension,
  NodeMetadata,
  StructureEdge,
  TEXT_PRIMARY,
  TEXT_SECONDARY,
  WHITE,
  calculateNodePositions,
  calculate_node_positions,
  renderInteractive,
  render_interactive,
  type FlowStructureLike,
  type FlowVisualizationNodeMetadata,
  type NodePosition,
} from "./flow-visualization.js";
export {
  JsonFlowPersistence,
  PersistDecorator,
  PersistenceDecorator,
  SQLiteFlowPersistence,
  SQLiteFlowPersistenceAlias,
  SqliteFlowPersistence,
  deserializePendingFeedbackContext,
  persist,
  persist_state,
  serializePendingFeedbackContext,
  sqliteFlowPersistence,
  sqlite_flow_persistence,
  FlowPersistence,
  LOG_MESSAGES,
  type PendingFeedbackRecord,
  type PersistDecoratorOptions,
} from "./flow-persistence.js";
export {
  GuardrailResult,
  GuardrailResult as StandardGuardrailResult,
  GuardrailCallable,
  HallucinationGuardrail,
  LLMGuardrail,
  LLMGuardrailResult,
  processGuardrail,
  process_guardrail,
  serializeGuardrailForJson,
  serializeGuardrailsForJson,
  serialize_guardrail_for_json,
  serialize_guardrails_for_json,
  setHallucinationGuardrailHook,
  set_hallucination_guardrail_hook,
  GuardrailType,
  GuardrailsType,
  type AsyncGuardrailCallable,
  type HallucinationGuardrailHook,
  type HallucinationGuardrailOptions,
  type LLMGuardrailOptions,
} from "./guardrail.js";
export {
  SyncHumanInputProvider,
  AsyncExecutorContext,
  ExecutorContext,
  HumanInputProvider,
  get_provider,
  getHumanInputProvider,
  reset_provider,
  set_provider,
  setHumanInputProvider,
  type HumanInputRequest,
} from "./human-input.js";
export {
  AfterLLMCallHook,
  AfterLLMCallHookCallable,
  AfterLLMCallHookMethod,
  AfterLLMCallHookType,
  AfterToolCallHook,
  AfterToolCallHookCallable,
  AfterToolCallHookMethod,
  AfterToolCallHookType,
  AsyncHTTPTransport,
  BaseInterceptor,
  BeforeLLMCallHook,
  BeforeLLMCallHookCallable,
  BeforeLLMCallHookMethod,
  BeforeLLMCallHookType,
  BeforeToolCallHook,
  BeforeToolCallHookCallable,
  BeforeToolCallHookMethod,
  BeforeToolCallHookType,
  ContextT,
  Hook,
  LLMCallHookContext,
  P as HookP,
  R as HookR,
  ReturnT,
  ToolCallHookContext,
  HTTPTransportKwargs,
  U,
  U as HookU,
  afterLlmCall,
  afterToolCall,
  after_llm_call,
  after_tool_call,
  beforeLlmCall,
  beforeToolCall,
  before_llm_call,
  before_tool_call,
  clearAfterLlmCallHooks,
  clearAfterToolCallHooks,
  clearAllGlobalHooks,
  clearAllLlmCallHooks,
  clearAllToolCallHooks,
  clearBeforeLlmCallHooks,
  clearBeforeToolCallHooks,
  clear_after_llm_call_hooks,
  clear_after_tool_call_hooks,
  clear_all_global_hooks,
  clear_all_llm_call_hooks,
  clear_all_tool_call_hooks,
  clear_before_llm_call_hooks,
  clear_before_tool_call_hooks,
  getAfterLlmCallHooks,
  getAfterToolCallHooks,
  getBeforeLlmCallHooks,
  getBeforeToolCallHooks,
  get_after_llm_call_hooks,
  get_after_tool_call_hooks,
  get_before_llm_call_hooks,
  get_before_tool_call_hooks,
  registerAfterLlmCallHook,
  registerAfterToolCallHook,
  registerBeforeLlmCallHook,
  registerBeforeToolCallHook,
  register_after_llm_call_hook,
  register_after_tool_call_hook,
  register_before_llm_call_hook,
  register_before_tool_call_hook,
  unregisterAfterLlmCallHook,
  unregisterAfterToolCallHook,
  unregisterBeforeLlmCallHook,
  unregisterBeforeToolCallHook,
  unregister_after_llm_call_hook,
  unregister_after_tool_call_hook,
  unregister_before_llm_call_hook,
  unregister_before_tool_call_hook,
} from "./hooks.js";
export {
  createReadFileTool,
  extractInputFilesFromInputs,
  renderInputFiles,
  withReadFileTool,
  isStructuredInputFile,
  type ExtractedInputFiles,
  type InputFile,
  type InputFiles,
} from "./input-files.js";
export {
  ConsoleInputProvider,
  FlowConfig,
  flowConfig,
} from "./input-provider.js";
export {
  CSVKnowledgeSource,
  CrewDoclingSource,
  ExcelKnowledgeSource,
  JSONKnowledgeSource,
  BaseFileKnowledgeSource,
  BaseKnowledgeSource,
  Knowledge,
  KnowledgeStorage,
  BaseKnowledgeStorage,
  PDFKnowledgeSource,
  SourceHelper,
  StringKnowledgeSource,
  TextFileKnowledgeSource,
  extractKnowledgeContext,
  type ExcelKnowledgeSourceOptions,
  type ExcelSheetData,
  type ExcelTextExtractor,
  type ExcelWorkbookData,
  type FileKnowledgeSourceOptions,
  type KnowledgeOptions,
  type KnowledgeQueryOptions,
  type KnowledgeSearchResult,
  type KnowledgeSource,
  type KnowledgeStorageOptions,
  type BaseKnowledgeSourceOptions,
  type PDFKnowledgeSourceOptions,
  type PDFTextExtractor,
  type StringKnowledgeSourceOptions,
} from "./knowledge.js";
export {
  AccumulatedToolArgs,
  ANTHROPIC_PREFIXES,
  BaseLLM,
  ConfiguredLLM,
  ConfiguredLLM as LLM,
  DEFAULT_LLM_MODEL,
  DEFAULT_CONTEXT_WINDOW_SIZE,
  DEFAULT_SUPPORTS_STOP_WORDS,
  Delta,
  ANTHROPIC_MODELS,
  AnthropicModels,
  AZURE_MODELS,
  AzureModels,
  BEDROCK_MODELS,
  BedrockModels,
  GROQ_MODELS,
  GroqModels,
  HUGGINGFACE_MODELS,
  HuggingFaceModels,
  LITELLM_PARAMS,
  LLM_ENV_VARS,
  LLM_PROVIDER_ALIASES,
  UNACCEPTED_LLM_ENV_ATTRIBUTES,
  FunctionLLM,
  FunctionArgs,
  CONTEXT_WINDOW_USAGE_RATIO,
  CACHE_BREAKPOINT_KEY,
  ENV_VARS,
  GEMINI_MODELS,
  GeminiModels,
  LLM_CONTEXT_WINDOW_SIZES,
  JSON_URL,
  LocalFileUploader,
  MAX_CONTEXT,
  MAX_CONTEXT_WINDOW_SIZE,
  MIN_CONTEXT,
  MIN_CONTEXT_WINDOW_SIZE,
  MODELS,
  NVIDIA_NIM_MODELS,
  NvidiaNimModels,
  OLLAMA_MODELS,
  OllamaModels,
  OPENAI_MODELS,
  OpenAIModels,
  PROVIDERS,
  SAMBANOVA_MODELS,
  SambanovaModels,
  SUPPORTED_NATIVE_PROVIDERS,
  StreamingChoices,
  WATSON_MODELS,
  WatsonModels,
  UsageMetrics,
  addUsageMetrics,
  callLLM,
  callStopOverride,
  call_stop_override,
  canonicalLLMProvider,
  canonical_llm_provider,
  clearLLMProviders,
  contextWindowSizeForModel,
  context_window_size_for_model,
  createLLM,
  createLLMClient,
  create_llm,
  emptyUsageMetrics,
  estimateTokens,
  estimateUsageMetrics,
  extract_tool_info,
  extractProvider,
  extract_provider,
  inferProviderFromModel,
  infer_provider_from_model,
  getCurrentCallId,
  get_current_call_id,
  getLLMUsageMetrics,
  hasLLMUsageMetrics,
  isEmptyUsageMetrics,
  llmCallContext,
  llm_call_context,
  log_tool_conversion,
  llmViaEnvironmentOrFallback,
  llm_via_environment_or_fallback,
  markCacheBreakpoint,
  mark_cache_breakpoint,
  matchesProviderPattern,
  matches_provider_pattern,
  normalizeLLMEnvKeyName,
  normalize_llm_env_key_name,
  registerLLMProvider,
  resolveLLMProvider,
  resolveLLMModelSpec,
  resolve_llm_model_spec,
  safe_tool_conversion,
  sanitize_function_name,
  stripCacheBreakpoint,
  strip_cache_breakpoint,
  subtractUsageMetrics,
  unregisterLLMProvider,
  validateContextWindowSizes,
  validate_function_name,
  validate_context_window_sizes,
  validateModelInConstants,
  validate_model_in_constants,
  validateStructuredOutput,
  validate_structured_output,
  type CacheBreakpointMessage,
  type BaseLLMOptions,
  type CreateLLMEnvironment,
  type CreateLLMValue,
  type LLMModelSpec,
  type LLMEnvVarSpec,
  JsonResponseFormat,
  type LLMEmitCallCompletedOptions,
  type LLMEmitCallFailedOptions,
  type LLMEmitCallStartedOptions,
  type LLMEmitStreamChunkOptions,
  type LLMEmitThinkingChunkOptions,
  type LLMAvailableFunction,
  type LLMHandleToolExecutionOptions,
  type LLMMessageInput,
  type LLMCallOptions,
  type LLMClient,
  type LLMFunction,
  type LLMResponse,
  type LocalFileUpload,
  type UsageMetricsOptions,
  type UsageMetricsLike,
  type StructuredOutputValidator,
} from "./llm.js";
export {
  VERSION,
  __version__,
  check_version,
  get_latest_version_from_pypi,
  is_current_version_yanked,
  is_newer_version_available,
} from "./version.js";
export {
  LiteAgent,
  type LiteAgentGuardrail,
  type LiteAgentGuardrailResult,
  type LiteAgentKickoffInput,
  type LiteAgentKickoffOptions,
  type LiteAgentOptions,
} from "./lite-agent.js";
export {
  LiteAgentOutput,
  TodoExecutionResult,
  type LiteAgentOutputOptions,
  type TodoExecutionResultOptions,
} from "./lite-agent-output.js";
export {
  Logger,
  PRINTER,
  Printer,
  ColoredText,
  PrinterColor,
  renderColoredText,
  render_colored_text,
  setSuppressConsoleOutput,
  set_suppress_console_output,
  shouldSuppressConsoleOutput,
  should_suppress_console_output,
  suppressLogging,
  suppressWarnings,
  suppress_logging,
  suppress_warnings,
  withSuppressedOutput,
  with_suppressed_output,
  type LoggerOptions,
} from "./logger.js";
export {
  clearNamedLocks,
  clear_named_locks,
  getLockName,
  get_lock_name,
  lock,
  withLock,
  with_lock,
} from "./lock-store.js";
export {
  Memory,
  DEFAULT_VECTOR_DIM,
  EncodingFlow,
  EncodingState,
  ItemState,
  LanceDBStorage,
  ConsolidationAction,
  ConsolidationPlan,
  ExtractedMemories,
  ExtractedMetadata,
  MemoryScope,
  MemorySlice,
  MemoryAnalysis,
  MemoryConfig,
  MemoryMatch,
  MemoryRecord,
  QueryAnalysis,
  QdrantEdgeStorage,
  RecallMemorySchema,
  RecallMemoryTool,
  RecallFlow,
  RecallState,
  RememberSchema,
  RememberTool,
  ScopeInfo,
  StorageBackend,
  VECTOR_NAME,
  analyzeForConsolidation,
  analyzeForSave,
  analyzeQuery,
  analyze_for_consolidation,
  analyze_for_save,
  analyze_query,
  createMemoryTools,
  create_memory_tools,
  extractMemoriesFromContent,
  extract_memories_from_content,
  compute_composite_score,
  embed_text,
  embed_texts,
  joinScopePaths,
  join_scope_paths,
  normalize_scope_path,
  sanitize_scope_name,
  type MemoryInfo,
  type MemoryOptions,
  type MemoryMatchOptions,
  type MemoryRecordOptions,
  type MemoryTreeNode,
  type MemoryVectorSearchOptions,
  type MemoryVectorStorageLike,
  type ScopeInfoOptions,
} from "./memory.js";
export {
  BaseTransport,
  HTTPTransport,
  MCPClient,
  MCP_CONNECTION_TIMEOUT,
  MCP_DISCOVERY_TIMEOUT,
  MCP_MAX_RETRIES,
  MCPToolResolver,
  MCPReadStream,
  MCPServerHTTP,
  MCPServerSSE,
  MCPServerStdio,
  MCPServerConfig,
  MCP_TOOL_EXECUTION_TIMEOUT,
  MCPWriteStream,
  SSETransport,
  StaticToolFilter,
  StdioTransport,
  ToolFilter,
  ToolFilterContext,
  TransportType,
  createDynamicToolFilter,
  createStaticToolFilter,
  create_dynamic_tool_filter,
  create_static_tool_filter,
  isMCPServerConfig,
  is_mcp_server_config,
  type MCPServerHTTPOptions,
  type MCPServerSSEOptions,
  type MCPServerStdioOptions,
  type MCPToolDefinition,
  type MCPClientOptions,
  type MCPToolResolverOptions,
  type ToolFilterContextOptions,
} from "./mcp.js";
export { getCrewMetadata, type MethodEntry, type MethodKind } from "./metadata.js";
export { CrewOutput, TaskOutput, type CrewOutputOptions, type TaskOutputOptions } from "./outputs.js";
export {
  CrewPlanner,
  PlanPerTask,
  PlannerTaskPydanticOutput,
  parsePlannerTaskOutput,
  type CrewPlannerOptions,
  type PlannerTaskOutput,
} from "./planning.js";
export {
  PlusAPI,
  buildEnvWithAllToolCredentials,
  buildEnvWithToolRepositoryCredentials,
  build_env_with_all_tool_credentials,
  build_env_with_tool_repository_credentials,
  createAuthenticatedPlusApi,
  create_authenticated_plus_api,
  type AvailableExport,
  type CreateCrewPayload,
  type CrewDeploymentSpec,
  type EnvVarEntry,
  type HttpMethod,
  type PlusAPIOptions,
  type PlusApiResponse,
  type PublishToolPayload,
  type ToolCredentialOptions,
  type ToolMetadata,
  type ToolsMetadataPayload,
  type TraceBatchInitPayload,
  type TraceBatchMetadata,
  type TraceEventsPayload,
  type TraceExecutionContext,
  type TraceExecutionMetadata,
  type TraceFailedPayload,
  type TraceFinalizePayload,
} from "./plus-api.js";
export { RPMController, RpmController } from "./rpm.js";
export {
  BaseRAGStorage,
  BaseClient,
  BaseEmbeddingsProvider,
  BaseEmbeddingsCallable,
  BaseCollectionAddParams,
  BaseCollectionParams,
  BaseCollectionSearchParams,
  BaseRecord,
  BaseRagConfig,
  AzureProviderSpec,
  BedrockProviderSpec,
  BedrockProvider,
  ChromaDBClient,
  ChromaDBConfig,
  ChromaDBClientType,
  ChromaDBCollectionCreateParams,
  ChromaDBCollectionSearchParams,
  ChromaEmbeddingFunctionWrapper,
  ChromaFactoryModule,
  ClientMethodMismatchError,
  CohereProvider,
  CohereProviderConfig,
  CohereProviderSpec,
  AsyncEmbeddingFunction,
  BasicConditions,
  CommonCreateFields,
  CreateCollectionParams,
  CustomEmbeddingFunction,
  CustomProvider,
  CustomProviderConfig,
  CustomProviderSpec,
  DEFAULT_CHROMADB_DATABASE,
  DEFAULT_CHROMADB_STORAGE_PATH,
  DEFAULT_CHROMADB_TENANT,
  DEFAULT_COLLECTION,
  DEFAULT_DATABASE,
  DEFAULT_EMBEDDING_MODEL,
  DEFAULT_QDRANT_EMBEDDING_MODEL,
  DEFAULT_QDRANT_STORAGE_PATH,
  DEFAULT_RAG_CONFIG_CLASS,
  DEFAULT_RAG_CONFIG_PATH,
  DEFAULT_STORAGE_PATH,
  DEFAULT_TENANT,
  DEFAULT_VECTOR_PARAMS,
  DISCRIMINATOR,
  DType32,
  DType64,
  DTypeCommon,
  Documents,
  Embedding,
  EmbeddingFunction,
  Embeddings,
  Embeddable,
  ExtractedSearchParams,
  FilterCondition,
  FloatingType,
  AzureProvider,
  AzureProviderConfig,
  BedrockProviderConfig,
  CohereEmbeddingFunction,
  GenerativeAiProvider,
  GenerativeAiProviderSpec,
  GenerativeAiProviderConfig,
  GoogleGenerativeAiEmbeddingFunction,
  GoogleGenAIVertexEmbeddingFunction,
  HuggingFaceEmbeddingFunction,
  HuggingFaceProvider,
  HuggingFaceProviderConfig,
  HuggingFaceProviderSpec,
  InstructorProvider,
  InstructorProviderConfig,
  InstructorProviderSpec,
  Images,
  INVALID_CHARS_PATTERN,
  IntegerType,
  IPV4_PATTERN,
  JinaEmbeddingFunction,
  JinaProvider,
  JinaProviderConfig,
  JinaProviderSpec,
  MetadataFilter,
  MetadataFilterValue,
  MAX_COLLECTION_LENGTH,
  MIN_COLLECTION_LENGTH,
  NumberType,
  OllamaEmbeddingFunction,
  OllamaProvider,
  OllamaProviderConfig,
  OllamaProviderSpec,
  ONNXProvider,
  ONNXProviderConfig,
  ONNXProviderSpec,
  OpenAIProvider,
  OpenAIEmbeddingFunction,
  OpenAIProviderConfig,
  OpenAIProviderSpec,
  OpenCLIPProvider,
  OpenCLIPProviderConfig,
  OpenCLIPProviderSpec,
  PreparedDocuments,
  PreparedSearchParams,
  PyEmbedding,
  PyEmbeddings,
  QdrantClient,
  QdrantClientParams,
  QdrantClientType,
  QdrantCollectionCreateParams,
  QdrantConfig,
  QdrantEmbeddingFunctionWrapper,
  QdrantFactoryModule,
  QueryEmbedding,
  PROVIDER_PATHS,
  RagConfigType,
  RagError,
  RoboflowEmbeddingFunction,
  RoboflowProvider,
  RoboflowProviderConfig,
  RoboflowProviderSpec,
  SearchResult,
  ScalarType,
  SentenceTransformerProvider,
  SentenceTransformerProviderConfig,
  SentenceTransformerProviderSpec,
  StructuralConditions,
  Text2VecProvider,
  Text2VecProviderConfig,
  Text2VecProviderSpec,
  VertexAIProvider,
  VertexAIProviderSpec,
  VertexAIProviderConfig,
  VoyageAIEmbeddingFunction,
  VoyageAIProvider,
  VoyageAIProviderConfig,
  VoyageAIProviderSpec,
  WatsonXEmbeddingFunction,
  WatsonXProvider,
  WatsonXProviderConfig,
  WatsonXProviderSpec,
  MissingChromaDBConfig,
  MissingQdrantConfig,
  buildEmbedder,
  buildEmbedderFromDict,
  buildEmbedderFromProvider,
  build_embedder,
  build_embedder_from_dict,
  build_embedder_from_provider,
  clearEmbeddingProviderBuilders,
  clear_embedding_provider_builders,
  clearRagClientFactories,
  clearRagConfig,
  clear_rag_config,
  clear_rag_client_factories,
  createClient,
  create_aws_session,
  createContentId,
  createRagClient,
  create_client,
  create_content_id,
  getEmbeddingFunction,
  getRagClient,
  getRagConfig,
  get_rag_client,
  get_rag_config,
  get_embedding_function,
  maybeCastOneToMany,
  maybe_cast_one_to_many,
  normalizeBaseRecord,
  normalizeEmbeddings,
  normalizeRagConfig,
  normalize_base_record,
  normalize_embeddings,
  normalize_rag_config,
  registerEmbeddingProviderBuilder,
  register_embedding_provider_builder,
  registerRagClientFactory,
  register_rag_client_factory,
  setRagConfig,
  set_rag_config,
  unregisterEmbeddingProviderBuilder,
  unregister_embedding_provider_builder,
  unregisterRagClientFactory,
  unregister_rag_client_factory,
  validateEmbeddings,
  validate_embeddings,
  AllowedEmbeddingProviders,
  EmbedderConfig,
  ProviderSpec,
  type AllowedEmbeddingProvider,
  type BaseProviderSpec,
  type BaseRAGStorageOptions,
  type BaseRecordOptions,
  type BaseRagConfigOptions,
  type ChromaDBConfigOptions,
  type ChromaDBSettings,
  type Embeddable as EmbeddableValue,
  type EmbeddingFunction as EmbeddingFunctionType,
  type EmbeddingProviderBuilder,
  type QdrantClientParams as QdrantClientParamsOptions,
  type QdrantConfigOptions,
  type RagClient,
  type RagClientFactory,
  type RagMetadata,
  type RagMetadataValue,
  type RagProvider,
  type SearchResultOptions,
  type TypedEmbeddingFunction,
} from "./rag.js";
export { RWLock } from "./rw-lock.js";
export {
  CrewProject,
  agentOptionsFromConfig,
  extractAvailableExports,
  extractToolsMetadata,
  extract_available_exports,
  extract_tools_metadata,
  fetchCrews,
  fetch_crews,
  ensureCrewProject,
  getCrewInstance,
  getCrews,
  getFlowInstance,
  getFlows,
  get_crew_instance,
  get_crews,
  get_flow_instance,
  get_flows,
  isValidTool,
  is_valid_tool,
  loadConfig,
  mapAgentVariables,
  mapTaskVariables,
  taskOptionsFromConfig,
  type AgentConfig as ProjectAgentConfig,
  type ConfigRecord,
  type ConfigSource,
  type CrewProjectLike,
  type CrewProjectState,
  type ProjectConfig,
  type ProjectModuleLike,
  type TaskConfig as ProjectTaskConfig,
  type ToolMetadata as ProjectToolMetadata,
} from "./project.js";
export {
  CREW_AI_NAMESPACE,
  Fingerprint,
  SecurityConfig,
  coerceSecurityConfig,
  type FingerprintDict,
  type FingerprintMetadata,
  type FingerprintOptions,
  type SecurityConfigOptions,
} from "./security.js";
export {
  CLI_SETTINGS_KEYS,
  CREWAI_ENTERPRISE_DEFAULT_OAUTH2_AUDIENCE,
  CREWAI_ENTERPRISE_DEFAULT_OAUTH2_CLIENT_ID,
  CREWAI_ENTERPRISE_DEFAULT_OAUTH2_DOMAIN,
  CREWAI_ENTERPRISE_DEFAULT_OAUTH2_PROVIDER,
  CREWAI_TRAINED_AGENTS_FILE_ENV,
  DEFAULT_CLI_SETTINGS,
  DEFAULT_CONFIG_PATH,
  DEFAULT_CREWAI_ENTERPRISE_URL,
  EMITTER_COLOR,
  HIDDEN_SETTINGS_KEYS,
  KNOWLEDGE_DIRECTORY,
  MAX_FILE_NAME_LENGTH,
  NOT_SPECIFIED,
  READONLY_SETTINGS_KEYS,
  Settings,
  TRAINED_AGENTS_DATA_FILE,
  TRAINING_DATA_FILE,
  USER_SETTINGS_KEYS,
  dbStoragePath,
  db_storage_path,
  getProjectDirectoryName,
  getWritableConfigPath,
  get_project_directory_name,
  get_writable_config_path,
  hasUserDeclinedTracing,
  has_user_declined_tracing,
  isTracingEnabled,
  is_tracing_enabled,
  loadUserData,
  load_user_data,
  saveUserData,
  save_user_data,
  updateUserData,
  update_user_data,
  userDataFile,
  user_data_file,
  type SettingsData,
  type SettingsOptions,
  type UserData,
} from "./settings.js";
export {
  getUserId,
  get_user_id,
  isFirstExecution,
  isTracingEnabledInContext,
  is_first_execution,
  is_tracing_enabled_in_context,
  markFirstExecutionCompleted,
  markFirstExecutionDone,
  mark_first_execution_completed,
  mark_first_execution_done,
  onFirstExecutionTracingConfirmation,
  on_first_execution_tracing_confirmation,
  promptUserForTraceViewing,
  prompt_user_for_trace_viewing,
  resetTracingEnabled,
  reset_tracing_enabled,
  safeSerializeToDict,
  safe_serialize_to_dict,
  setFirstTimeTraceHook,
  setSuppressTracingMessages,
  setTracingEnabled,
  set_first_time_trace_hook,
  set_suppress_tracing_messages,
  set_tracing_enabled,
  shouldAutoCollectFirstTimeTraces,
  shouldEnableTracing,
  shouldSuppressTracingMessages,
  should_auto_collect_first_time_traces,
  should_enable_tracing,
  should_suppress_tracing_messages,
  truncateMessages,
  truncate_messages,
  type SuppressTracingMessagesToken,
  type TracingEnabledToken,
} from "./tracing-utils.js";
export {
  CheckpointConfig,
  CheckpointEventType,
  EdgeType,
  EventNode,
  EventRecord,
  JsonProvider,
  RuntimeState,
  SqliteProvider,
  apply_checkpoint,
  coerceCheckpointConfig,
  detectProvider,
  detect_provider,
  type BaseProvider as BaseCheckpointProvider,
  type CheckpointConfigOptions,
  type CheckpointOption,
  type CheckpointProviderOptions,
  type CheckpointTrigger,
  type RuntimeStateOptions,
} from "./state.js";
export { StepExecutionContext, StepResult } from "./step-execution-context.js";
export {
  CrewStreamingOutput,
  FlowStreamingOutput,
  StreamChunk,
  StreamChunkType,
  ToolCallChunk,
  StreamingState,
  StreamingOutputBase,
  TaskInfo,
  createAsyncChunkGenerator,
  createChunkGenerator,
  createStreamingState,
  create_async_chunk_generator,
  create_chunk_generator,
  create_streaming_state,
  logger,
  logger as streamingLogger,
  registerCleanup,
  register_cleanup,
  signalEnd,
  signalError,
  signal_end,
  signal_error,
  type StreamChunkOptions,
} from "./streaming.js";
export {
  TrainingConverter,
  type TrainingConverterField,
  type TrainingConverterLLM,
  type TrainingConverterModel,
  type TrainingConverterOptions,
} from "./training-converter.js";
export {
  CrewTrainingHandler,
  type TrainingData,
  type TrainingDataStore,
} from "./training-handler.js";
export {
  I18N,
  I18N_DEFAULT,
  clearI18NCache,
  clear_i18n_cache,
  getI18N,
  get_i18n,
  type PromptCatalog,
  type PromptKind,
  type PromptLeaf,
} from "./i18n.js";
export {
  interpolate_only,
  sanitize_tool_name,
  slugify,
  type InterpolationValue,
} from "./string-utils.js";
export {
  FORMAT_TYPE_MAP,
  JsonSchemaInfo,
  ModelDescription,
  OPENAI_SUPPORTED_FORMATS,
  addConstToOneOfVariants,
  addKeyInDictRecursively,
  add_const_to_oneof_variants,
  add_key_in_dict_recursively,
  buildRichFieldDescription,
  build_rich_field_description,
  convertOneOfToAnyOf,
  convert_oneof_to_anyof,
  createModelFromSchema,
  create_model_from_schema,
  ensureAllPropertiesRequired,
  ensureTypeInSchemas,
  ensure_all_properties_required,
  ensure_type_in_schemas,
  fixDiscriminatorMappings,
  fix_discriminator_mappings,
  forceAdditionalPropertiesFalse,
  force_additional_properties_false,
  generateModelDescription,
  generate_model_description,
  liftTopLevelAnyOf,
  lift_top_level_anyof,
  resolveRefs,
  resolve_refs,
  sanitizeToolParamsForAnthropicStrict,
  sanitizeToolParamsForBedrockStrict,
  sanitizeToolParamsForOpenAIStrict,
  sanitize_tool_params_for_anthropic_strict,
  sanitize_tool_params_for_bedrock_strict,
  sanitize_tool_params_for_openai_strict,
  serializeModelClass,
  serialize_model_class,
  stripNullFromTypes,
  stripUnsupportedFormats,
  strip_null_from_types,
  strip_unsupported_formats,
  type JsonSchema,
} from "./schema-utils.js";
export {
  Prompts,
  StandardPromptResult,
  SystemPromptResult,
  type PromptAgentLike,
  type PromptComponent,
  type PromptsOptions,
  type StandardPromptResultOptions,
  type SystemPromptResultOptions,
} from "./prompts.js";
export {
  DisclosureLevel,
  ENV_VAR,
  ExperimentalFeatureDisabledError,
  INSTRUCTIONS,
  MAX_DESCRIPTION_LENGTH,
  MAX_SKILL_NAME_LENGTH,
  METADATA,
  MIN_SKILL_NAME_LENGTH,
  RESOURCES,
  ResourceDirName,
  SKILL_FILENAME,
  SKILL_NAME_PATTERN,
  Skill,
  SkillCacheManager,
  SkillFrontmatter,
  SkillNotCachedError,
  SkillParseError,
  activateSkill,
  activate_skill,
  discoverSkills,
  discover_skills,
  formatSkillContext,
  format_skill_context,
  is_enabled,
  isRegistryRef,
  is_registry_ref,
  loadResources,
  loadSkillInstructions,
  loadSkillMetadata,
  loadSkillResources,
  load_resources,
  load_skill_instructions,
  load_skill_metadata,
  load_skill_resources,
  parseFrontmatter,
  parseRegistryRef,
  parseSkillMd,
  parse_frontmatter,
  parse_registry_ref,
  parse_skill_md,
  resolveRegistryRef,
  resolve_registry_ref,
  require_experimental_skills,
  SkillMetadata,
  validateDirectoryName,
  validate_directory_name,
  type SkillFrontmatterOptions,
} from "./skills.js";
export {
  ConditionalTask,
  Task,
  interpolateOnly,
  type ConditionalTaskCondition,
  type ConditionalTaskOptions,
  type Guardrail,
  type TaskExecutionOptions,
  type TaskInputFile,
  type TaskInputFiles,
  type TaskOutputConverter,
  type TaskOptions,
} from "./task.js";
export {
  KickoffTaskOutputsSQLiteStorage,
  KickoffTaskOutputsSqliteStorage,
  TaskOutputStorageHandler,
  TaskOutputStorageHandlerAlias,
  defaultTaskOutputStoragePath,
  default_task_output_storage_path,
  type KickoffTaskOutputsStorage,
  type StoredTaskOutput,
  type TaskOutputStorageRecord,
  type TaskOutputStorageUpdate,
} from "./task-output-storage.js";
export {
  AddImageTool,
  AddImageToolSchema,
  AgentTools,
  AskQuestionTool,
  AskQuestionToolSchema,
  BaseAgentTool,
  BaseTool,
  CacheHandler,
  CacheTools,
  CrewStructuredTool,
  DelegateWorkTool,
  DelegateWorkToolSchema,
  EnvVar,
  InMemoryToolCache,
  InstructorToolCalling,
  MCPNativeTool,
  MCPToolWrapper,
  ReadFileTool,
  ReadFileToolSchema,
  StructuredTool,
  ToolCalling,
  ToolResult,
  ToolUsage,
  ToolUsageError,
  OPENAI_BIGGER_MODELS,
  ToolsHandler,
  ToolUsageLimitExceededError,
  aexecuteToolAndCheckFinality,
  aexecute_tool_and_check_finality,
  build_schema_hint,
  buildToolContext,
  createFunctionTool,
  create_function_tool,
  createTool,
  create_tool,
  executeToolAndCheckFinality,
  execute_tool_and_check_finality,
  normalizeToolCalling,
  normalizeToolInput,
  renderToolsDescription,
  sanitizeToolName,
  to_langchain,
  validateArgs,
  type AgentLikeForTool,
  type AgentToolsOptions,
  type BaseToolOptions,
  type EnvVarOptions,
  type MCPNativeToolOptions,
  type MCPToolWrapperOptions,
  type StructuredToolFromFunctionOptions,
  type StructuredToolOptions,
  type ToolDecoratorOptions,
  type ToolFunction,
  type ToolCache,
  type ToolCacheReadResult,
  type ToolArgumentSpec,
  type ToolArgumentType,
  type ToolArgsSchema,
  type ToolCallingLike,
  type ToolCallingOptions,
  type ToolInvocationInput,
  type ToolResultOptions,
  type ToolUsageOptions,
  type ToolsHandlerOptions,
} from "./tools.js";
export {
  CREWAI_TELEMETRY_BASE_URL,
  CREWAI_TELEMETRY_SERVICE_NAME,
  RecordedSpan,
  SafeOTLPSpanExporter,
  Telemetry,
  addAgentFingerprintToSpan,
  addCrewAndTaskAttributes,
  addCrewAttributes,
  addTaskAttributes,
  add_agent_fingerprint_to_span,
  add_crew_and_task_attributes,
  add_crew_attributes,
  add_task_attributes,
  closeSpan,
  close_span,
  type AddAttributeFn,
  type SpanLike,
} from "./telemetry.js";
export {
  LLMMessage,
  OutputFormat,
  Process,
  Tool,
  create_literals_from_strings,
  type AgentStep,
  type AgentStepCallback,
  type CrewKickoffCallback,
  type InputValues,
  type MaybePromise,
  type TaskCallback,
  type ToolContext,
} from "./types.js";
export {
  TokenCalcHandler,
  type TokenProcessLike,
  type TokenUsageLike,
} from "./token-counter-callback.js";
export type { UtilityLLMMessage } from "./utility-types.js";
export {
  crewJsonReplacer,
  crewJsonStringify,
  crew_json_stringify,
  callableToString,
  callable_to_string,
  clearCallableRegistry,
  clear_callable_registry,
  adapter,
  getProjectAttribute,
  getProjectDescription,
  getProjectName,
  getProjectVersion,
  getCrewaiVersion,
  get_crewai_version,
  get_project_attribute,
  get_project_description,
  get_project_name,
  get_project_version,
  COMPONENTS,
  CrewContext,
  CrewJSONEncoder,
  DEFAULT_TTL,
  ImportedDefinition,
  InternalInstructor,
  UNACCEPTED_ATTRIBUTES,
  console,
  get_crew_context,
  importAndValidateDefinition,
  import_and_validate_definition,
  registerCallable,
  register_callable,
  stringToCallable,
  string_to_callable,
  unregisterCallable,
  unregister_callable,
  validateImportPath,
  validate_import_path,
  parseToml,
  parse_toml,
  readToml,
  read_toml,
  require,
  requireModule,
  require_module,
  reset_memories_command,
  toSerializable,
  toString,
  to_serializable,
  to_string,
  AttributeError,
  ImportError,
  OptionalDependencyError,
  Serializable,
  SerializableCallable,
  SerializablePrimitive,
  type ResetMemoriesCommandOptions,
  type ToSerializableOptions,
} from "./utilities.js";

export const version = CREWAI_VERSION;

export class CrewAIPlugin {
  readonly kind = "CrewAIPlugin";

  getClassDecoratorHook(fullname: string): ((ctx: { cls?: { info?: { fullname?: string; names?: Record<string, unknown> } } }) => void) | null {
    if (fullname === "crewai.project.CrewBase" || fullname === "crewai.project.crew_base.CrewBase") {
      return (ctx) => {
        CrewAIPlugin.crewBaseHook(ctx);
      };
    }
    return null;
  }

  get_class_decorator_hook(fullname: string): ReturnType<CrewAIPlugin["getClassDecoratorHook"]> {
    return this.getClassDecoratorHook(fullname);
  }

  private static crewBaseHook(ctx: { cls?: { info?: { fullname?: string; names?: Record<string, unknown> } } }): void {
    const info = ctx.cls?.info;
    if (!info) {
      return;
    }
    info.names ??= {};
    info.names.agents_config = {
      kind: "MDEF",
      name: "agents_config",
      fullname: `${info.fullname ?? "Crew"}.agents_config`,
      type: "dict[str, Any]",
    };
    info.names.tasks_config = {
      kind: "MDEF",
      name: "tasks_config",
      fullname: `${info.fullname ?? "Crew"}.tasks_config`,
      type: "dict[str, Any]",
    };
  }
}

export function plugin(): CrewAIPlugin {
  return new CrewAIPlugin();
}

export function enable_verbose_stdout_logging(): void {}

export const openai_agents_module = Object.freeze({ kind: "openai_agents_module" });
export const agents_module = Object.freeze({ kind: "agents_module" });
export const D = Object.freeze({ kind: "D" });
export const RagContext = Object.freeze({ kind: "RagContext" });
export const SupportedProviderConfig = Object.freeze({ kind: "SupportedProviderConfig" });
export const SupportedProvider = Object.freeze({ kind: "SupportedProvider" });

export function extract_knowledge_context(items: readonly unknown[] = []): string {
  return items.map((item) => String(item)).join("\n");
}

export class KnowledgeConfig {
  readonly sources: readonly unknown[];

  constructor(sources: readonly unknown[] = []) {
    this.sources = sources;
  }
}

export function extract_json_from_llm_response(text: string): unknown {
  const start = text.indexOf("{");
  const end = text.lastIndexOf("}");
  if (start < 0 || end < start) {
    return null;
  }
  return JSON.parse(text.slice(start, end + 1));
}

export class AgentMeta {
  readonly kind = "AgentMeta";
}

export function process_status_update(update: unknown): unknown {
  return update;
}

export const http_url_adapter = Object.freeze({ kind: "http_url_adapter" });

export type AgentCardSigningAlgorithm =
  | "RS256"
  | "RS384"
  | "RS512"
  | "ES256"
  | "ES384"
  | "ES512"
  | "PS256"
  | "PS384"
  | "PS512";

export type AgentCardSigningConfigOptions = {
  enabled?: boolean;
  privateKeyPath?: string | null;
  private_key_path?: string | null;
  privateKeyPem?: string | null;
  private_key_pem?: string | null;
  keyId?: string | null;
  key_id?: string | null;
  algorithm?: AgentCardSigningAlgorithm;
};

export class AgentCardSigningConfig {
  readonly enabled: boolean;
  readonly privateKeyPath: string | null;
  readonly private_key_path: string | null;
  readonly privateKeyPem: string | null;
  readonly private_key_pem: string | null;
  readonly keyId: string | null;
  readonly key_id: string | null;
  readonly algorithm: AgentCardSigningAlgorithm;

  constructor(options: AgentCardSigningConfigOptions | boolean = {}) {
    const config = typeof options === "boolean" ? { enabled: options } : options;
    this.enabled = config.enabled ?? true;
    this.privateKeyPath = config.privateKeyPath ?? config.private_key_path ?? null;
    this.private_key_path = this.privateKeyPath;
    this.privateKeyPem = config.privateKeyPem ?? config.private_key_pem ?? null;
    this.private_key_pem = this.privateKeyPem;
    this.keyId = config.keyId ?? config.key_id ?? null;
    this.key_id = this.keyId;
    this.algorithm = config.algorithm ?? "RS256";

    const hasPath = this.privateKeyPath !== null;
    const hasPem = this.privateKeyPem !== null;
    if (!hasPath && !hasPem) {
      throw new Error("Either private_key_path or private_key_pem must be provided");
    }
    if (hasPath && hasPem) {
      throw new Error("Only one of private_key_path or private_key_pem should be provided");
    }
  }

  getPrivateKey(): string {
    if (this.privateKeyPem !== null) {
      return this.privateKeyPem;
    }
    if (this.privateKeyPath !== null) {
      return readFileSync(this.privateKeyPath, "utf8");
    }
    throw new Error("No private key configured");
  }

  get_private_key(): string {
    return this.getPrivateKey();
  }
}

export async function download_skill(org: string, name: string): Promise<unknown> {
  await Promise.resolve();
  return { org, name };
}
